import{CHUNK,getNearbyChunks}from'./world.js';import{drawCharacter}from'./characters.js';
export function createEngine({canvas,state,onInteract}){const ctx=canvas.getContext('2d'),keys=new Set();let running=false,last=0,time=0,mode='factory',joy={x:0,y:0};const residents=[{id:'oren',x:480,y:180},{id:'pinki',x:-520,y:300},{id:'simon',x:900,y:-380},{id:'vineria',x:-850,y:-500}];
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}
function input(){let x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)+joy.x,y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0)+joy.y;const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m}}
function sky(){const day=(Math.sin(time*.00003)+1)/2,g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,`rgb(${45+day*70},${70+day*130},${110+day*125})`);g.addColorStop(.63,'#b9e8de');g.addColorStop(.64,'#78ba61');g.addColorStop(1,'#477f42');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);const sx=innerWidth*.82,sy=95+Math.sin(time*.0002)*10;ctx.fillStyle='#ffd84c';ctx.strokeStyle='#e89b31';ctx.lineWidth=6;ctx.beginPath();ctx.arc(sx,sy,44,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#3c2a36';ctx.beginPath();ctx.arc(sx-14,sy-7,4,0,7);ctx.arc(sx+14,sy-7,4,0,7);ctx.fill();ctx.beginPath();ctx.arc(sx,sy+6,14,0,Math.PI);ctx.stroke();for(let i=0;i<6;i++){const x=((time*.015+i*270)%(innerWidth+300))-180,y=55+(i%3)*65;ctx.fillStyle='#ffffffb8';ctx.beginPath();ctx.ellipse(x,y,72,26,0,0,7);ctx.ellipse(x+45,y-13,52,30,0,0,7);ctx.fill()}}
function building(b,x,y){const colors={factory:'#aeb6c4',shop:'#ffbd59',housePlot:'#ec83aa',music:'#7969dc',cave:'#615969'},labels={factory:'角色生产中心',shop:'节拍商店',housePlot:'住宅地块',music:'音乐广场',cave:'山洞'};ctx.fillStyle=colors[b.kind];ctx.strokeStyle='#3c3150';ctx.lineWidth=7;ctx.beginPath();ctx.roundRect(x-70,y-75,140,120,18);ctx.fill();ctx.stroke();ctx.fillStyle='#493047';ctx.fillRect(x-18,y-10,36,55);ctx.fillStyle='#fff';ctx.font='bold 17px sans-serif';ctx.textAlign='center';ctx.fillText(labels[b.kind],x,y-90)}
function world(){const cam=state.player;if(mode==='factory'){ctx.fillStyle='#293047';ctx.fillRect(0,innerHeight*.2,innerWidth,innerHeight*.8);ctx.fillStyle='#4b5872';ctx.fillRect(innerWidth/2-180,innerHeight/2-150,360,300);ctx.fillStyle='#9ef4ed';ctx.fillRect(innerWidth/2-105,innerHeight/2-90,210,170);ctx.fillStyle='#fff';ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText('角色生产舱',innerWidth/2,innerHeight/2-115);drawCharacter(ctx,state.player.character,innerWidth/2,innerHeight/2+55,1.25,'idle',time);drawCharacter(ctx,'fun-bot',innerWidth/2-250,innerHeight/2+75,1.1,'idle',time);return}const chunks=getNearbyChunks(state.seed,cam.x,cam.y,2),ox=innerWidth/2-cam.x,oy=innerHeight/2-cam.y;for(const ch of chunks){const bx=ch.cx*CHUNK+ox,by=ch.cy*CHUNK+oy;ctx.fillStyle=ch.biome==='stone'?'#73a968':ch.biome==='flowers'?'#83c966':'#78bd60';ctx.fillRect(bx,by,CHUNK+1,CHUNK+1);ctx.fillStyle='#d5bc82';if(ch.roads.horizontal)ctx.fillRect(bx,by+CHUNK/2-42,CHUNK,84);if(ch.roads.vertical)ctx.fillRect(bx+CHUNK/2-42,by,84,CHUNK);for(const d of ch.decorations){const x=bx+d.x,y=by+d.y;if(d.kind==='tree'){ctx.fillStyle='#6e4b35';ctx.fillRect(x-8,y,16,35);ctx.fillStyle='#3b8d51';ctx.beginPath();ctx.arc(x,y-12,28*d.size,0,7);ctx.fill()}else{ctx.fillStyle=d.kind==='flower'?'#fff18a':'#70816d';ctx.beginPath();ctx.arc(x,y,5*d.size,0,7);ctx.fill()}}for(const b of ch.buildings)if(b.kind!=='factory')building(b,bx+b.x,by+b.y)}for(const r of residents)drawCharacter(ctx,r.id,r.x+ox,r.y+oy,.9,'idle',time);drawCharacter(ctx,state.player.character,innerWidth/2,innerHeight/2,1.05,input().x||input().y?'walk':'idle',time)}
function loop(now){if(!running)return;const dt=Math.min(32,now-last||16);last=now;time=now;const v=input();if(mode==='world'){state.player.x+=v.x*dt*.19;state.player.y+=v.y*dt*.19}sky();world();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space')onInteract?.()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('resize',resize);resize();return{start(){if(!running){running=true;requestAnimationFrame(loop)}},stop(){running=false},resize,setMode(v){mode=v},setJoystick(x,y){joy={x,y}},setPlayerCharacter(id){state.player.character=id},getMode:()=>mode}}

