import{CHUNK,getNearbyChunks}from'./world.js';import{drawCharacter,characterById}from'./characters.js';
const RESIDENT_IDS=['oren','raddy','clukr','fun-bot','vineria','gray','brud','garnold','owakcx','pinki','simon','sky','durple','mr-tree','wenda','jevin','black','mr-fun-computer'];
export const distanceTo=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function createEngine({canvas,state,onInteract}){const ctx=canvas.getContext('2d'),keys=new Set();let running=false,last=0,time=0,mode='factory',joy={x:0,y:0};
  const residentHomes=RESIDENT_IDS.map((id,i)=>({id,x:(i%6-2.5)*230,y:(Math.floor(i/6)-1)*260+520}));
  const residents=residentHomes.map((h,i)=>({id:h.id,x:h.x+70+(i%2)*40,y:h.y+115,home:h,phase:i*.71}));
  const factoryDoor={kind:'factory',x:0,y:0,label:'角色生产中心'};
  function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}
  function input(){let x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)+joy.x,y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0)+joy.y;const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m}}
  function drawSkyCharacter(ctx,id,x,y,scale,t){drawCharacter(ctx,id,x,y,scale,'idle',t)}
  function sky(){const day=(Math.sin(time*.00003)+1)/2,g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,`rgb(${45+day*70},${70+day*130},${110+day*125})`);g.addColorStop(.63,'#b9e8de');g.addColorStop(.64,'#78ba61');g.addColorStop(1,'#477f42');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight)}
  function celestialOverlay(){const band=155,g=ctx.createLinearGradient(0,0,0,band);g.addColorStop(0,'#70c9f0cc');g.addColorStop(1,'#bceaff00');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,band);for(let i=0;i<4;i++){const x=((time*.012+i*390)%(innerWidth+280))-160,y=78+(i%2)*45;ctx.fillStyle='#ffffffb8';ctx.beginPath();ctx.ellipse(x,y,62,20,0,0,7);ctx.ellipse(x+38,y-11,43,25,0,0,7);ctx.fill()}drawSkyCharacter(ctx,'mr-sun',innerWidth-105,122+Math.sin(time*.0002)*8,.68,time)}
  function building(b,x,y,label){const colors={factory:'#aeb6c4',shop:'#ffbd59',housePlot:'#ec83aa',music:'#7969dc',cave:'#615969',residentHome:'#f3a875'},labels={factory:'角色生产中心',shop:'节拍商店',housePlot:'住宅地块',music:'音乐广场',cave:'山洞',residentHome:'居民的家'};ctx.fillStyle=colors[b.kind]||'#ddd';ctx.strokeStyle='#3c3150';ctx.lineWidth=7;if(b.kind==='cave'){ctx.beginPath();ctx.ellipse(x,y,68,46,0,Math.PI,0);ctx.lineTo(x+68,y+35);ctx.lineTo(x-68,y+35);ctx.closePath();ctx.fill();ctx.stroke()}else{ctx.beginPath();ctx.roundRect(x-70,y-75,140,120,18);ctx.fill();ctx.stroke();ctx.fillStyle='#493047';ctx.fillRect(x-18,y-10,36,55)}ctx.fillStyle='#fff';ctx.font='bold 16px sans-serif';ctx.textAlign='center';ctx.fillText(label||labels[b.kind]||'',x,y-88)}
  function isGoingHome(){return Math.sin(time*.00003)<-.25}
  function residentPosition(r){if(isGoingHome())return{x:r.home.x,y:r.home.y+70};return{x:r.x+Math.sin(time*.00035+r.phase)*80,y:r.y+Math.cos(time*.00027+r.phase)*45}}
  function worldEntities(){const out=[factoryDoor];for(const ch of getNearbyChunks(state.seed,state.player.x,state.player.y,2))for(const b of ch.buildings)out.push({...b,x:ch.cx*CHUNK+b.x,y:ch.cy*CHUNK+b.y});for(const h of residentHomes)out.push({kind:'residentHome',id:h.id,x:h.x,y:h.y,label:`${characterById(h.id).name}的家`});for(const r of residents){const p=residentPosition(r);out.push({kind:'resident',id:r.id,x:p.x,y:p.y,label:characterById(r.id).name})}return out}
  function getNearbyInteractable(){if(mode==='factory')return{kind:'factoryExit',x:state.player.x,y:state.player.y,label:'离开生产中心'};let best=null,bestD=115;for(const e of worldEntities()){if(e.kind==='factory'&&e.x===CHUNK/2&&e.y===CHUNK/2)continue;const d=distanceTo(state.player,e);if(d<bestD){best=e;bestD=d}}return best}
  function drawFactory(){ctx.fillStyle='#293047';ctx.fillRect(0,innerHeight*.2,innerWidth,innerHeight*.8);ctx.fillStyle='#4b5872';ctx.fillRect(innerWidth/2-180,innerHeight/2-150,360,300);ctx.fillStyle='#9ef4ed';ctx.fillRect(innerWidth/2-105,innerHeight/2-90,210,170);ctx.fillStyle='#6b4860';ctx.fillRect(innerWidth-170,innerHeight/2-65,95,160);ctx.fillStyle='#fff';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.fillText('角色生产舱',innerWidth/2,innerHeight/2-115);ctx.fillText('出口',innerWidth-122,innerHeight/2-78);drawCharacter(ctx,state.player.character,innerWidth/2,innerHeight/2+55,1.25,'idle',time);drawCharacter(ctx,'fun-bot',innerWidth/2-250,innerHeight/2+75,1.1,'idle',time)}
  function drawWorld(){const cam=state.player,chunks=getNearbyChunks(state.seed,cam.x,cam.y,2),ox=innerWidth/2-cam.x,oy=innerHeight/2-cam.y;for(const ch of chunks){const bx=ch.cx*CHUNK+ox,by=ch.cy*CHUNK+oy;ctx.fillStyle=ch.biome==='stone'?'#73a968':ch.biome==='flowers'?'#83c966':'#78bd60';ctx.fillRect(bx,by,CHUNK+1,CHUNK+1);ctx.fillStyle='#d5bc82';if(ch.roads.horizontal)ctx.fillRect(bx,by+CHUNK/2-42,CHUNK,84);if(ch.roads.vertical)ctx.fillRect(bx+CHUNK/2-42,by,84,CHUNK);for(const d of ch.decorations){const x=bx+d.x,y=by+d.y;if(d.kind==='tree'){ctx.fillStyle='#6e4b35';ctx.fillRect(x-8,y,16,35);ctx.fillStyle='#3b8d51';ctx.beginPath();ctx.arc(x,y-12,28*d.size,0,7);ctx.fill()}else{ctx.fillStyle=d.kind==='flower'?'#fff18a':'#70816d';ctx.beginPath();ctx.arc(x,y,5*d.size,0,7);ctx.fill()}}for(const b of ch.buildings)building(b,bx+b.x,by+b.y)}building(factoryDoor,ox,oy,'角色生产中心');for(const h of residentHomes)building({kind:'residentHome'},h.x+ox,h.y+oy,`${characterById(h.id).name}的家`);for(const r of residents){const p=residentPosition(r);drawCharacter(ctx,r.id,p.x+ox,p.y+oy,.86,isGoingHome()?'walk':'idle',time)}drawCharacter(ctx,state.player.character,innerWidth/2,innerHeight/2,1.05,input().x||input().y?'walk':'idle',time);celestialOverlay();const target=getNearbyInteractable();if(target){ctx.fillStyle='#17182ddd';ctx.fillRect(innerWidth/2-100,innerHeight/2+75,200,35);ctx.fillStyle='#ffe55f';ctx.textAlign='center';ctx.font='bold 15px sans-serif';ctx.fillText(`互动：${target.label}`,innerWidth/2,innerHeight/2+98)}}
  function loop(now){if(!running)return;const dt=Math.min(32,now-last||16);last=now;time=now;const v=input();if(mode==='world'){state.player.x+=v.x*dt*.19;state.player.y+=v.y*dt*.19}sky();mode==='factory'?drawFactory():drawWorld();requestAnimationFrame(loop)}
  addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space')onInteract?.(getNearbyInteractable())});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('resize',resize);resize();return{start(){if(!running){running=true;requestAnimationFrame(loop)}},stop(){running=false},resize,setMode(v){mode=v},setJoystick(x,y){joy={x,y}},setPlayerCharacter(id){state.player.character=id},getNearbyInteractable,getMode:()=>mode,residentHomes,isGoingHome}}
