/* Runnable, local applications. Every mount returns a cleanup function. */
(() => {
  const catalog = {calculator:['算','计算器'],notes:['记','便签本'],tasks:['单','待办清单'],memory:['牌','记忆翻牌'],piano:['琴','小钢琴'],dance:['舞','节奏音乐跳舞游戏'],blocks3d:['立','我的世界 3D']};
  const songs = [{name:'芯片起舞',bpm:96,scale:[0,4,7,12,7,4,2,7]},{name:'霓虹对决',bpm:120,scale:[0,3,7,10,12,10,7,3]},{name:'月光律动',bpm:84,scale:[0,5,9,12,9,7,5,2]},{name:'像素冲刺',bpm:140,scale:[0,7,12,7,3,10,15,10]},{name:'彩虹派对',bpm:110,scale:[0,2,4,7,9,7,4,2]}];
  const chart = song => {const bpm=Math.max(40,Math.min(240,Number(song.bpm)||120)),length=song.duration?Math.max(0,Math.floor((Math.min(900,song.duration)-3)*bpm/60)+1):64;return Array.from({length},(_,i)=>({time:2+i*60/bpm,lane:(i*3+Math.floor(i/4))%4,done:false})).filter(n=>!song.vocalWindows||song.vocalWindows.some(([from,to])=>n.time>=from+1.8&&n.time<=to));};
  const audioFileAllowed=file=>/\.(mp3|wav|ogg|m4a|aac|flac|webm)$/i.test(file.name)&&file.size>0&&file.size<=25*1024*1024;
  const matchesSong=(song,query,sprunkiOnly=false)=>(!sprunkiOnly||/sprunki/i.test(song.name))&&song.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  const leadCharacter=song=>song?.mix?.some(stem=>stem.id==='computer')||song?.vocalWindows?.length?'computer':song?.cast?.[0]||null;
  const grade = delta => Math.abs(delta)<=.09 ? 100 : Math.abs(delta)<=.2 ? 60 : 0;
  const songSources=[
    {name:'Incredibox Sprunki — Friend Like You',artist:'Horror Skunx',url:'https://www.youtube.com/watch?v=Lz66RAjtCgw'},
    {name:'Sprunki Song',artist:'BENJIxScarlett',url:'https://www.youtube.com/watch?v=e6um0c7gP6s'},
    {name:'Sprunki Super Tunes Phase 1',artist:'PghLFilms',url:'https://music.apple.com/us/song/1828848981'},
    {name:'More sprunki Mixes（三首可下载混音）',artist:'Ender',url:'https://ender-75.itch.io/more-sprunki-mixes'}
  ];
  if(typeof module!=='undefined') { module.exports={catalog,songs,chart,grade,audioFileAllowed,matchesSong,songSources,leadCharacter}; return; }
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('apps-'+key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem('apps-'+key,JSON.stringify(value));return true;}catch{return false;}};
  const el=(tag,text,parent)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n;};
  const btn=(parent,text,fn)=>{const b=el('button',text,parent);b.type='button';b.onclick=fn;return b;};
  function sound(ctx,freq,start,duration=.16,type='sine',volume=.08){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,start);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(ctx.destination);o.onended=()=>{o.disconnect();g.disconnect();};o.start(start);o.stop(start+duration);}
  function mount(id,host){host.classList.add('extra-app');
    if(id==='dance')return dance(host); if(id==='blocks3d')return blocks(host);
    if(id==='calculator'){
      const input=el('input',undefined,host);input.type='text';input.placeholder='输入两个数字，例如 12 × 3';input.setAttribute('aria-label','计算式');const out=el('output','',host);
      const calc=()=>{const m=input.value.match(/^\s*(-?\d+(?:\.\d+)?)\s*([+\-*/×÷])\s*(-?\d+(?:\.\d+)?)\s*$/);if(!m){out.textContent='请输入 数字 运算符 数字';return;}const a=+m[1],b=+m[3];const result={'+':()=>a+b,'-':()=>a-b,'*':()=>a*b,'×':()=>a*b,'/':()=>a/b,'÷':()=>a/b}[m[2]]();out.textContent=Number.isFinite(result)?String(result):'不能除以零';};btn(host,'计算',calc);input.onkeydown=e=>{if(e.key==='Enter')calc();};
    }else if(id==='notes'){
      const area=el('textarea',undefined,host);area.setAttribute('aria-label','便签内容');area.value=String(read('notes',''));area.placeholder='写下想记住的事情…';const status=el('small','自动保存在本机',host);area.oninput=()=>status.textContent=save('notes',area.value)?'已保存':'保存失败，请复制文字留存';
    }else if(id==='tasks'){
      const input=el('input',undefined,host);input.placeholder='新的待办';input.setAttribute('aria-label','新的待办');const list=el('div',undefined,host);let items=read('tasks',[]);if(!Array.isArray(items))items=[];items=items.filter(x=>x&&typeof x.text==='string');
      const render=()=>{list.replaceChildren();items.forEach((item,i)=>{const row=el('label',undefined,list),check=el('input',undefined,row);check.type='checkbox';check.checked=!!item.done;el('span',item.text,row);check.onchange=()=>{item.done=check.checked;save('tasks',items);};btn(row,'删除',()=>{items.splice(i,1);save('tasks',items);render();});});};const add=()=>{if(!input.value.trim())return;items.push({text:input.value.trim(),done:false});input.value='';save('tasks',items);render();};btn(host,'添加待办',add);input.onkeydown=e=>{if(e.key==='Enter')add();};render();
    }else if(id==='memory'){
      const info=el('p','找到所有相同图案',host),grid=el('div',undefined,host);grid.className='memory-grid';let timer=0,first=null,locked=false,matches=0,moves=0;
      const start=()=>{clearTimeout(timer);first=null;locked=false;matches=0;moves=0;info.textContent='找到所有相同图案';grid.replaceChildren();const cards=['🌈','🎵','💻','🌟','🌈','🎵','💻','🌟'];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}cards.forEach(symbol=>{const b=btn(grid,'?',()=>{if(locked||b.disabled||b===first)return;b.textContent=symbol;if(!first){first=b;return;}moves++;if(first.textContent===symbol){b.disabled=first.disabled=true;matches++;first=null;info.textContent=matches===4?`全部找到！用了 ${moves} 次`:`已找到 ${matches}/4 对`;}else{locked=true;timer=setTimeout(()=>{first.textContent=b.textContent='?';first=null;locked=false;},700);}});});};btn(host,'重新洗牌',start);start();return()=>clearTimeout(timer);
    }else if(id==='piano'){
      el('p','点击琴键演奏',host);let ctx;const keys=el('div',undefined,host);keys.className='piano-keys';['Do','Re','Mi','Fa','Sol','La','Si','Do↑'].forEach((name,i)=>btn(keys,name,async()=>{try{ctx??=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();sound(ctx,261.63*2**([0,2,4,5,7,9,11,12][i]/12),ctx.currentTime,.6,'triangle');}catch{keys.title='浏览器没有开启声音';}}));return()=>{if(ctx)ctx.close();};
    }
    return()=>{};
  }
  function dance(host){
    host.innerHTML='<div class="dance-toolbar"><label>歌曲 <select aria-label="选择歌曲"></select></label></div><p class="dance-status" role="status">自制曲目 · 按方向键或点箭头，接住落到白线的音符</p><div class="dance-stage"><div class="dance-player"><div class="dance-monitor"><div class="dance-face"><span class="dance-eyes"><i></i><i></i></span><span class="dance-mouth"></span></div></div><small>电脑先生</small></div><div class="dance-lanes"><canvas aria-label="四方向下落音符"></canvas><div class="dance-targets"></div></div><div class="dance-rival"><img alt="对战角色"><small></small></div></div>';
    const selects=host.querySelectorAll('select'),songSelect=selects[0],status=host.querySelector('.dance-status'),canvas=host.querySelector('canvas'),g=canvas.getContext('2d'),player=host.querySelector('.dance-player'),rival=host.querySelector('.dance-rival');
    let library=[...(window.DanceMusic?.tracks||[]),...songs.map((s,i)=>({...s,id:'practice-'+i,cast:[['oren','pinki'],['wenda','gray'],['sky','durple'],['simon','raddy'],['vineria','brud']][i]}))];
    const computerAppearance=player.innerHTML;
    const picture=()=>{const lead=leadCharacter(selected);player.replaceChildren();player.classList.remove('singing');if(lead==='computer')player.innerHTML=computerAppearance;else{const img=el('img',undefined,player);img.className='dance-lead-character';img.src=lead?'./assets/sprunki-2d/'+lead+'.png':'./assets/sprunki-2d/oren.png';img.alt=lead||'节奏搭档';el('small',lead||'节奏搭档',player);}player.dataset.character=lead||'partner';rival.replaceChildren();for(const id of selected?.cast||[]){if(id===lead)continue;const figure=el('div',undefined,rival),img=el('img',undefined,figure);img.src='./assets/sprunki-2d/'+id+'.png';img.alt=id;el('small',id,figure);}if(!selected?.cast?.length)el('small','电脑先生独唱',rival);};
    let ctx,raf=0,active=true,running=false,notes=[],startTime=0,score=0,combo=0,rivalScore=0,nextSound=0,moveUntil=0,rivalBeat=-1,selected=library[0],media=null,mediaURL=null,db=null,starting=false,importing=false,video=null,playSession=0;const arrows=['←','↓','↑','→'];
    const libraryBox=el('details',undefined);libraryBox.className='dance-library';host.prepend(libraryBox);el('summary','更多歌曲 / 本机音频',libraryBox);
    const cards=el('div',undefined);cards.className='dance-song-cards';cards.setAttribute('aria-label','点歌即玩');host.prepend(cards);
    const videoBox=el('div',undefined,host.querySelector('.dance-stage'));videoBox.className='dance-video';videoBox.hidden=true;
    const search=el('input',undefined,libraryBox);search.type='search';search.placeholder='搜索歌名';search.setAttribute('aria-label','搜索歌名');
    const filterLabel=el('label','只看歌名带 SPRUNKI 的歌曲',libraryBox),filter=el('input',undefined,filterLabel);filter.type='checkbox';
    const importLabel=el('label','批量导入歌曲',libraryBox),files=el('input',undefined,importLabel);files.type='file';files.accept='.mp3,.wav,.ogg,.m4a,.aac,.flac,.webm';files.multiple=true;files.disabled=true;
    const libraryStatus=el('p','正在打开本机歌曲库…',libraryBox);libraryStatus.setAttribute('role','status');
    const tempoLabel=el('label','节拍速度 BPM',libraryBox),tempo=el('input',undefined,tempoLabel);tempo.type='number';tempo.min=40;tempo.max=240;tempo.value=120;tempo.setAttribute('aria-label','歌曲节拍速度');
    el('small','导入完整音频后可选歌对战，保存在本机。每首最多 25 MB、15 分钟。导入曲目的箭头按所设节拍生成，可调整 BPM；不是原曲官方谱面。',libraryBox);
    const sources=el('details',undefined,libraryBox);sources.className='dance-song-sources';el('summary','找歌曲 · 原曲与作者页面',sources);el('p','这些是歌曲来源链接，需要联网打开。拿到可播放的音频文件后，可用上面的导入按钮加入对战。',sources);
    for(const source of songSources){const link=el('a',source.name+' — '+source.artist,sources);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';}
    const remove=btn(libraryBox,'移除所选导入歌曲',async()=>{if(!selected?.imported||running||starting)return;try{await transaction(['tracks','audio'],'readwrite',tx=>{tx.objectStore('tracks').delete(selected.id);tx.objectStore('audio').delete(selected.id);});library=library.filter(s=>s.id!==selected.id);renderSongs();libraryStatus.textContent='已移除歌曲';}catch{libraryStatus.textContent='移除失败，请重试';}});
    function transaction(stores,mode,action){return new Promise((resolve,reject)=>{if(!db){reject(Error('歌曲库不可用'));return;}const tx=db.transaction(stores,mode);let req;try{req=action(tx);}catch(e){reject(e);return;}tx.oncomplete=()=>resolve(req?.result);tx.onerror=tx.onabort=()=>reject(tx.error||Error('存储失败'));});}
    const request=indexedDB.open('computer-dance-library',1);request.onupgradeneeded=()=>{request.result.createObjectStore('tracks',{keyPath:'id'});request.result.createObjectStore('audio');};request.onsuccess=async()=>{db=request.result;if(!active){db.close();return;}try{const tracks=await transaction(['tracks'],'readonly',tx=>tx.objectStore('tracks').getAll());if(!active)return;library.push(...tracks);renderSongs();files.disabled=false;libraryStatus.textContent=tracks.length?`已载入 ${tracks.length} 首导入歌曲`:'三首多角色合奏已保存在本机，无需互联网；在线原曲单独标明。';}catch{libraryStatus.textContent='歌曲库读取失败；练习曲仍可玩。';}};request.onerror=()=>libraryStatus.textContent='本机存储不可用，无法保存导入歌曲。';
    function chosen(){selected=library.find(s=>s.id===songSelect.value);picture();tempo.value=selected?.bpm||120;tempo.disabled=!selected?.imported;remove.disabled=!selected?.imported;begin.disabled=!selected||starting;if(running||starting)lock(true);}
    function renderSongs(){const old=songSelect.value;cards.replaceChildren();for(const track of library.filter(s=>s.video||s.mix)){const card=btn(cards,track.name+' · '+track.artist,()=>{stopAudio();search.value='';filter.checked=false;renderSongs();songSelect.value=track.id;chosen();begin.click();});card.dataset.song=track.id;} songSelect.replaceChildren();for(const s of library.filter(s=>matchesSong(s,search.value,filter.checked))){const o=el('option',`${s.name} · ${s.video?'在线原曲':s.mix?'离线合奏 · 练习谱面':s.imported?'原文件':'自制练习'} · ${Math.round(s.bpm*100)/100} BPM`,songSelect);o.value=s.id;}if([...songSelect.options].some(o=>o.value===old))songSelect.value=old;chosen();if(!selected){status.textContent='没有匹配歌曲。可清除筛选，或导入带 SPRUNKI 名字的音频文件。';}else if(!running&&!video&&!starting)status.textContent=`已选择：${selected.name} · 点上方歌名即可开始`;}
    search.oninput=filter.onchange=renderSongs;songSelect.onchange=()=>{stopAudio();chosen();begin.click();};
    tempo.onchange=async()=>{if(!selected?.imported)return;selected.bpm=Math.max(40,Math.min(240,Number(tempo.value)||120));tempo.value=selected.bpm;try{await transaction(['tracks'],'readwrite',tx=>tx.objectStore('tracks').put(selected));renderSongs();}catch{libraryStatus.textContent='节拍已更改，但保存失败。';}};
    function durationOf(file){return new Promise((resolve,reject)=>{const a=new Audio(),url=URL.createObjectURL(file);const timer=setTimeout(()=>finish(Error('读取超时')),10000);function finish(error){clearTimeout(timer);const duration=a.duration;a.removeAttribute('src');a.load();URL.revokeObjectURL(url);error?reject(error):resolve(duration);}a.onloadedmetadata=()=>finish();a.onerror=()=>finish(Error('格式不能播放'));a.preload='metadata';a.src=url;});}
    files.onchange=async()=>{if(running||starting)return;importing=true;files.disabled=true;const batch=[...files.files];let added=0;const failures=[];for(const file of batch){if(!active)break;if(!audioFileAllowed(file)){failures.push(file.name+'：格式不支持或超过 25 MB');continue;}const id=`file-${file.name}-${file.size}-${file.lastModified}`;if(library.some(s=>s.id===id))continue;try{const duration=await durationOf(file);if(!active)break;if(!Number.isFinite(duration)||duration<4||duration>900)throw Error('时长需为 4 秒至 15 分钟');const track={id,name:file.name.replace(/\.[^.]+$/,''),duration,bpm:120,imported:true};await transaction(['tracks','audio'],'readwrite',tx=>{tx.objectStore('tracks').put(track);tx.objectStore('audio').put(file,id);});library.push(track);added++;libraryStatus.textContent=`已导入 ${added} 首…`;}catch(e){failures.push(file.name+'：'+e.message);}}importing=false;if(active){files.value='';files.disabled=running||starting;renderSongs();libraryStatus.textContent=`已添加 ${added} 首。${failures.join('；')}`;}};
    function lock(value){files.disabled=value||importing||!db;songSelect.disabled=starting;search.disabled=filter.disabled=value;tempo.disabled=value||!selected?.imported;remove.disabled=value||!selected?.imported;}
    function stopAudio(){playSession++;running=false;resume.hidden=true;if(video){video.destroy();video=null;}videoBox.replaceChildren();videoBox.hidden=true;if(media){media.onended=media.onerror=null;media.pause();media.removeAttribute('src');media.load();media=null;}if(mediaURL){URL.revokeObjectURL(mediaURL);mediaURL=null;}if(ctx){ctx.close();ctx=null;}rival.style.transform='';player.classList.remove('singing');rival.querySelectorAll(':scope > div').forEach(f=>{f.classList.remove('singing');f.style.transform='';});lock(false);}
    function finish(){stopAudio();status.textContent=`${score>=rivalScore?'电脑先生获胜！':'对手获胜，再来一次！'} 你 ${score} : 对手 ${rivalScore}`;}
    const begin=btn(host.querySelector('.dance-toolbar'),'开始对战',async()=>{if(!selected||starting)return;starting=true;begin.disabled=true;stopAudio();const session=playSession;retry.hidden=true;resume.hidden=true;lock(true);cards.querySelectorAll('button').forEach(b=>b.disabled=true);try{status.textContent='正在准备：'+selected.name;notes=chart(selected);if(selected.mix)notes=notes.filter(n=>[[16,48],[64,112]].some(([a,b])=>n.time>=2+a*60/selected.bpm+1.8&&n.time<=2+b*60/selected.bpm));score=combo=rivalScore=nextSound=0;rivalBeat=-1;picture();if(selected.video){videoBox.hidden=false;const credit=el('p',selected.name+' — '+selected.artist+' · 在线原曲 · 练习谱面 / 舞台搭档',videoBox);const slot=el('div',undefined,videoBox);status.textContent='正在连接原曲…';const openedVideo=await window.DanceMusic.open(slot,selected,{
      loading:message=>{if(active&&session===playSession){running=false;status.textContent=message;}},
      state:(state,p)=>{if(!active||session!==playSession)return;resume.hidden=state===1;if(state===1){const duration=p.getDuration();if(duration>3&&notes.length!==chart({...selected,duration}).length)notes=chart({...selected,duration});running=true;status.textContent='正在播放：'+selected.name+' · 接住白线上的箭头';}else if(state===0)finish();else{running=false;status.textContent=state===3?'音乐缓冲中…':'点击原曲播放器的播放按钮继续';}},
      blocked:()=>{if(active&&session===playSession){running=false;resume.hidden=false;status.textContent='浏览器暂停了自动播放，请点“播放声音”';}},
      error:message=>{if(session===playSession){stopAudio();retry.hidden=false;status.textContent=message;}}
    });if(!active||session!==playSession){openedVideo?.destroy();return;}video=openedVideo;begin.textContent='重新开始';return;
    }else if(selected.mix){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const schedule=await window.DanceMusic.prepareMix(ctx,selected);if(!active||session!==playSession)return;startTime=ctx.currentTime;schedule(startTime);videoBox.hidden=true;}else if(selected.imported){const blob=await transaction(['audio'],'readonly',tx=>tx.objectStore('audio').get(selected.id));if(!active)return;if(!blob)throw Error('音频文件缺失');mediaURL=URL.createObjectURL(blob);media=new Audio(mediaURL);media.onended=finish;media.onerror=()=>{stopAudio();status.textContent='这首歌无法播放，请重新导入可播放的音频';};await media.play();}else{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();startTime=ctx.currentTime;}if(!active){stopAudio();return;}running=true;begin.textContent='重新开始';status.textContent=`正在播放：${selected.name}${selected.mix?' · 多角色离线合奏 / 练习谱面':''} · 用方向键或下方箭头接拍`;}catch(e){if(active&&session===playSession){stopAudio();retry.hidden=false;status.textContent='歌曲未能播放：'+e.message;}}finally{starting=false;begin.disabled=!selected;songSelect.disabled=false;cards.querySelectorAll('button').forEach(b=>b.disabled=false);}});
    const retry=btn(host.querySelector('.dance-toolbar'),'重试原曲',()=>begin.click());retry.hidden=true;const resume=btn(host.querySelector('.dance-toolbar'),'播放声音',()=>video?.playVideo());resume.hidden=true;
    btn(host.querySelector('.dance-toolbar'),'停止 / 换歌',()=>{if(starting)return;stopAudio();status.textContent='已停止，可以重新选择歌曲';});renderSongs();
    const time=()=>video?video.getCurrentTime():media?media.currentTime:(ctx?ctx.currentTime-startTime:0);
    function drawArrow(lane,x,y,size,color){g.save();g.translate(x,y);g.rotate([Math.PI,Math.PI/2,-Math.PI/2,0][lane]);g.beginPath();const points=[[-.46,-.19],[.02,-.19],[.02,-.47],[.49,0],[.02,.47],[.02,.19],[-.46,.19]];points.forEach(([a,b],i)=>i?g.lineTo(a*size,b*size):g.moveTo(a*size,b*size));g.closePath();g.fillStyle=color;g.strokeStyle='#10142c';g.lineWidth=Math.max(2,size*.045);g.lineJoin='round';g.fill();g.stroke();g.restore();}
    function hit(lane){if(!running)return;const t=time(),n=notes.find(n=>!n.done&&n.lane===lane&&Math.abs(n.time-t)<=.2);const points=n?grade(n.time-t):0;if(n){n.done=true;score+=points;combo++;}else combo=0;player.style.transform=['translateX(-12px)','translateY(12px)','translateY(-12px)','translateX(12px)'][lane];moveUntil=performance.now()+150;status.textContent=`${points===100?'完美':points?'接住了':'没接到'} · 得分 ${score} · 连击 ${combo} · 对手 ${rivalScore}`;}
    arrows.forEach((a,i)=>{const b=btn(host.querySelector('.dance-targets'),a,()=>hit(i));b.setAttribute('aria-label',['左','下','上','右'][i]+'方向落点');});const key=e=>{const i=['ArrowLeft','ArrowDown','ArrowUp','ArrowRight'].indexOf(e.key);if(i>=0&&!e.repeat&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();hit(i);}};document.addEventListener('keydown',key);
    function frame(){if(!active)return;raf=requestAnimationFrame(frame);const w=Math.max(120,Math.floor(canvas.clientWidth)),h=Math.max(110,Math.floor(canvas.clientHeight));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}g.clearRect(0,0,w,h);g.fillStyle='rgba(15,45,68,.22)';g.fillRect(0,0,w,h);const line=h*.8;g.strokeStyle='#fff';g.beginPath();g.moveTo(0,line);g.lineTo(w,line);g.stroke();g.font=Math.max(15,w/8)+'px sans-serif';g.textAlign='center';const colors=['#ff627d','#ffd45e','#5ce4ce','#9b8cff'];if(performance.now()>moveUntil)player.style.transform='';if(!running)return;const t=time();
      // Schedule music ahead against the audio clock, not animation-frame timing.
      while(!selected.video&&!selected.imported&&!selected.mix&&nextSound<notes.length&&notes[nextSound].time<t+.18){const i=nextSound++,n=notes[i],when=startTime+n.time;if(when>=ctx.currentTime){sound(ctx,220*2**(selected.scale[i%8]/12),when,.24,'triangle');sound(ctx,i%4===0?65:110,when,.1,'sine',.12);if(i%2===0)sound(ctx,880,when,.035,'square',.018);}}
      if(selected.mix){const songBeat=Math.max(0,(t-2)*selected.bpm/60),section=window.DanceMusic.sections.find(s=>songBeat>=s.from&&songBeat<s.to);if(section){rival.querySelectorAll(':scope > div').forEach((f,i)=>f.classList.toggle('singing',section.voices.includes(i)));player.classList.toggle('singing',section.voices.includes(5));}}
      if(selected.vocalWindows)player.classList.toggle('singing',selected.vocalWindows.some(([from,to])=>t>=from&&t<to));
      const beat=Math.floor(Math.max(0,t-2)/(60/selected.bpm));if(beat!==rivalBeat){rivalBeat=beat;if(player.classList.contains('singing')){player.style.transform=['translateX(-8px)','translateY(8px)','translateY(-10px)','translateX(8px)'][beat%4];moveUntil=performance.now()+250;}rival.querySelectorAll(':scope > div').forEach((f,i)=>{f.style.transform=['translateX(-10px)','translateY(10px)','translateY(-12px)','translateX(10px)'][(beat+i)%4];});}rivalScore=notes.filter((n,i)=>n.time<t&&i%5!==0).length*60;
      notes.forEach(n=>{if(!n.done&&t>n.time+.2){n.done=true;combo=0;}if(!n.done){const y=line-(n.time-t)*(line/1.8);if(y>-25&&y<h){drawArrow(n.lane,(n.lane+.5)*w/4,y,Math.min(64,w/4*.76),colors[n.lane]);}}});
      if(!selected.video&&!selected.imported&&t>(selected.mix?selected.duration:notes[notes.length-1].time+1))finish();
    }frame();return()=>{active=false;stopAudio();cancelAnimationFrame(raf);document.removeEventListener('keydown',key);db?.close();};
  }
  function blocks(host) { return window.VoxelWorld.mount(host); }
  window.ComputerApps={catalog,mount};
})();
