/* Runnable, local applications. Every mount returns a cleanup function. */
(() => {
  const catalog = {calculator:['算','计算器'],notes:['记','便签本'],tasks:['单','待办清单'],memory:['牌','记忆翻牌'],piano:['琴','小钢琴'],dance:['舞','节奏音乐跳舞游戏'],blocks3d:['立','我的世界 3D']};
  Object.assign(catalog,typeof module!=="undefined"?require("./arcade-games.js").catalog:window.ArcadeGames?.catalog);
  const songs = [{name:'芯片起舞',bpm:96,scale:[0,4,7,12,7,4,2,7]},{name:'霓虹对决',bpm:120,scale:[0,3,7,10,12,10,7,3]},{name:'月光律动',bpm:84,scale:[0,5,9,12,9,7,5,2]},{name:'像素冲刺',bpm:140,scale:[0,7,12,7,3,10,15,10]},{name:'彩虹派对',bpm:110,scale:[0,2,4,7,9,7,4,2]}];
  const chart = song => {if(song.reference)return song.notes.filter(n=>n.hit??n.side==='player').map(n=>({...n,done:false}));const bpm=Math.max(40,Math.min(240,Number(song.bpm)||120)),length=song.duration?Math.max(0,Math.floor((Math.min(900,song.duration)-3)*bpm/60)+1):64;return Array.from({length},(_,i)=>({time:2+i*60/bpm,lane:(i*3+Math.floor(i/4))%4,done:false})).filter(n=>!song.vocalWindows||song.vocalWindows.some(([from,to])=>n.time>=from+1.8&&n.time<=to));};
  const audioFileAllowed=file=>/\.(mp3|wav|ogg|m4a|aac|flac|webm)$/i.test(file.name)&&file.size>0&&file.size<=25*1024*1024;
  const matchesSong=(song,query,sprunkiOnly=false)=>(!sprunkiOnly||/sprunki/i.test(song.name))&&song.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  const leadCharacter=song=>song?.lead||(song?.mix?.some(stem=>stem.id==='computer')||song?.vocalWindows?.length?'computer':song?.cast?.[0]||null);
  const grade = delta => Math.abs(delta)<=.09 ? 100 : Math.abs(delta)<=.2 ? 60 : 0;
  const songSources=[{name:'Colorful Bunch · 原作者模组与曲目',artist:'Just_Camilo',url:'https://gamebanana.com/mods/585004'}
  ];
  if(typeof module!=='undefined') { module.exports={catalog,songs,chart,grade,audioFileAllowed,matchesSong,songSources,leadCharacter}; return; }
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('apps-'+key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem('apps-'+key,JSON.stringify(value));return true;}catch{return false;}};
  const el=(tag,text,parent)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n;};
  const btn=(parent,text,fn)=>{const b=el('button',text,parent);b.type='button';b.onclick=fn;return b;};
  function sound(ctx,freq,start,duration=.16,type='sine',volume=.08){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,start);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(ctx.destination);o.onended=()=>{o.disconnect();g.disconnect();};o.start(start);o.stop(start+duration);}
  function mount(id,host){host.classList.add('extra-app');
    if(window.ArcadeGames?.catalog[id])return window.ArcadeGames.mount(id,host);
    if(id==='dance')return dance(host); if(id==='blocks3d')return blocks(host);
    if(id==='calculator'){
      const input=el('input',undefined,host);input.type='text';input.placeholder='输入两个数字，例如 12 × 3';input.setAttribute('aria-label','计算式');const out=el('output','',host);
      const calc=()=>{const m=input.value.match(/^\s*(-?\d+(?:\.\d+)?)\s*([+\-*/×÷])\s*(-?\d+(?:\.\d+)?)\s*$/);if(!m){out.textContent='请输入 数字 运算符 数字';return;}const a=+m[1],b=+m[3];const result={'+':()=>a+b,'-':()=>a-b,'*':()=>a*b,'×':()=>a*b,'/':()=>a/b,'÷':()=>a/b}[m[2]]();out.textContent=Number.isFinite(result)?String(result):'不能除以零';};btn(host,'计算',calc);input.onkeydown=e=>{if(e.key==='Enter')calc();};
    }else if(id==='notes'){
      const area=el('textarea',undefined,host);area.setAttribute('aria-label','便签内容');area.value=String(read('notes',''));area.placeholder='写下想记住的事情…';const status=el('small','自动保存在本机',host);area.oninput=()=>status.textContent=save('notes',area.value)?'已保存':'保存失败，请复制文字留存';
    }else if(id==='tasks'){
      const input=el('input',undefined,host);input.placeholder='新的待办';input.setAttribute('aria-label','新的待办');const list=el('div',undefined,host);let items=read('tasks',[]);if(!Array.isArray(items))items=[];items=items.filter(x=>x&&typeof x.text==='string');
      const render=()=>{list.replaceChildren();items.forEach((item,i)=>{const row=el('label',undefined,list),check=el('input',undefined,row);check.type='checkbox';check.checked=!!item.done;el('span',item.text,row);check.onchange=()=>{item.done=check.checked;save('tasks',items);};btn(row,'删除',()=>{items.splice(i,1);save('tasks',items);render();});});};const add=()=>{if(!input.value.trim())return;items.push({text:input.value.trim(),done:false});input.value='';save('tasks',items);render();};btn(host,'添加待办',add);input.onkeydown=e=>{if(e.key==='Enter')add();};render();
    }else if(id==='memory'){
      const info=el('p','找到所有相同图案',host),grid=el('div',undefined,host);grid.className='memory-grid';let timer=0,first=null,locked=false,matches=0,moves=0;
      const start=()=>{clearTimeout(timer);first=null;locked=false;matches=0;moves=0;info.textContent='找到所有相同图案';grid.replaceChildren();const cards=['🌈','🎵','💻','🌟','🌈','🎵','💻','🌟'];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}cards.forEach(symbol=>{const b=btn(grid,'?',()=>{if(locked||b.disabled||b===first)return;b.textContent=symbol;if(!first){first=b;return;}moves++;if(first.textContent===symbol){b.disabled=first.disabled=true;matches++;first=null;info.textContent=matches===4?`全部找到！用了 ${moves} 次`:`已找到 ${matches}/4 对`;}else{locked=true;timer=setTimeout(()=>{first.textContent=b.textContent='?';first=null;locked=false;},700);}});});};btn(host,'重新洗牌',start);start();return()=>clearTimeout(timer);
    }else if(id==='piano'){
      el('p','点击琴键演奏',host);let ctx;const keys=el('div',undefined,host);keys.className='piano-keys';['Do','Re','Mi','Fa','Sol','La','Si','Do↑'].forEach((name,i)=>btn(keys,name,async()=>{try{ctx??=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();sound(ctx,261.63*2**([0,2,4,5,7,9,11,12][i]/12),ctx.currentTime,.6,'triangle');}catch{keys.title='浏览器没有开启声音';}}));return()=>{if(ctx)ctx.close();};
    }
    return()=>{};
  }
  function dance(host){
    host.innerHTML='<div class="dance-toolbar"><label>歌曲 <select aria-label="选择歌曲"></select></label></div><p class="dance-status" role="status">自制曲目 · 按方向键或点箭头，接住落到白线的音符</p><div class="dance-stage"><div class="dance-player"><div class="dance-monitor"><div class="dance-face"><span class="dance-eyes"><i></i><i></i></span><span class="dance-mouth"></span></div></div><small>电脑先生</small></div><div class="dance-lanes"><canvas aria-label="四方向下落音符"></canvas><div class="dance-targets"></div></div><div class="dance-rival"><img alt="对战角色"><small></small></div></div>';
    const selects=host.querySelectorAll('select'),songSelect=selects[0],status=host.querySelector('.dance-status'),canvas=host.querySelector('canvas'),g=canvas.getContext('2d'),player=host.querySelector('.dance-player'),rival=host.querySelector('.dance-rival');
    let library=[...(window.DanceMusic?.tracks||[]).map(t=>({...t,captions:read('lyrics-'+t.id,[])})),];
    const computerAppearance='<div class="dance-pose computer-pose" role="img" aria-label="电脑先生：帽子、显示器、支架和桌子"><span class="dance-screen-caption" hidden></span></div><small>电脑先生</small>';
    const poseRows={oren:0,pinki:1,gray:2,wenda:3};
    let liveMix=null,opponentCount=2,customMotion=false,castOverride={},pendingVoice=null,referenceRoles={},referenceEvent=0,referenceNote=0;
    const stage=host.querySelector('.dance-stage');
    const battle=el('div',undefined);battle.className='dance-battle';battle.innerHTML='<span>对手 <b data-rival-score>0</b></span><div class="dance-balance" role="progressbar" aria-label="我方对战优势" aria-valuemin="0" aria-valuemax="100" aria-valuenow="50"><i></i></div><span>我方 <b data-player-score>0</b></span><progress max="1" value="0" aria-label="歌曲进度"></progress>';stage.before(battle);
    const rack=el('div',undefined,host);rack.className='dance-rack';rack.setAttribute('aria-label','拖放角色声部');
    const rackHelp=el('p','拖一个角色到舞台上加入合奏；手机也可点角色加入。再点一次可静音。',host);rackHelp.className='dance-rack-help';
    function useOriginal(figure,id){figure.dataset.character=id;const art=window.DanceCast?.[id];if(window.DanceReference?.has(id)){figure.replaceChildren();const canvas=el('canvas',undefined,figure);canvas.className='dance-original';canvas.setAttribute('role','img');canvas.setAttribute('aria-label',art?.name||id);window.DanceReference.prepare([id]).then(()=>{if(canvas.isConnected)window.DanceReference.draw(canvas,id,'idle',0);}).catch(()=>{});el('small',art?.name||id,figure);return;}if(!art)return;figure.replaceChildren();const img=el('img',undefined,figure);img.className='dance-original';img.alt=art.name;img.src='./assets/sprunki-kiss-local/assets/'+art.idle;el('small',art.name,figure);}
    function animateOriginal(figure,t,singing){const id=figure.dataset.character,canvas=figure.querySelector('canvas.dance-original');if(canvas){const lane=Number(figure.dataset.pose??-1),age=Math.max(0,t-Number(figure.dataset.poseStart||0)),special=figure.dataset.special;let animation=special&&age<.6?special:lane>=0?['singLEFT','singDOWN','singUP','singRIGHT'][lane]:'idle',elapsed=lane>=0?age:(t%(60/(selected?.bpm||100)));if(selected?.mix&&id==='computer'&&singing&&!customMotion){const phase=Math.max(0,t-2)%9.6;animation=phase<.9?'hello':phase<2.2?'would':phase<3.2?'some':phase<7.7?'us':'fun';elapsed=phase%.6;}window.DanceReference.draw(canvas,id,animation,elapsed);return;}}
    function referenceFrame(t){if(!selected?.reference)return;for(let i=referenceEvent;i<selected.events.length&&selected.events[i].time<t+3;i++){const e=selected.events[i];if(e.character)window.DanceReference.prepare([e.character]).catch(()=>{});}let changed=false;
      while(referenceEvent<selected.events.length&&selected.events[referenceEvent].time<=t){const e=selected.events[referenceEvent++];if('character' in e){referenceRoles[e.side]=e.character;changed=true;}else{const figure=e.side==='player'?player:rival.querySelector('[data-role="'+e.side+'"]');if(figure){figure.dataset.special=e.animation;figure.dataset.poseStart=String(e.time);}}}if(changed)picture();
      while(referenceNote<selected.notes.length&&selected.notes[referenceNote].time<=t){const n=selected.notes[referenceNote++];if(!n.animate)continue;const figure=n.side==='player'?player:rival.querySelector('[data-role="'+n.side+'"]');if(!figure)continue;setPose(figure,n.lane,true);figure.dataset.poseStart=String(n.time);delete figure.dataset.special;const until=performance.now()+Math.max(0,n.time+Math.max(.2,n.hold)-t)*1000;if(figure===player)moveUntil=until;else figure.dataset.poseUntil=String(until);}
    }
    function updateBattle(t=0){battle.querySelector('[data-player-score]').textContent=score;battle.querySelector('[data-rival-score]').textContent=rivalScore;const advantage=Math.round(100*(score+500)/(score+rivalScore+1000)),bar=battle.querySelector('.dance-balance');bar.setAttribute('aria-valuenow',advantage);bar.style.setProperty('--player-share',advantage+'%');battle.querySelector('progress').value=Math.min(1,t/(selected?.duration||40));}
    function renderRack(){rack.replaceChildren();rack.hidden=rackHelp.hidden=false;rackHelp.textContent=selected?.reference?'原曲按原谱演唱；拖放下方角色可切换到自由合奏。Black 只保留正常外观。':'拖一个角色到舞台加入合奏；再点一次静音。二十位角色均为正常模式。';for(const stem of Object.keys(window.DanceCast).map(id=>({id}))){let suppressClickUntil=0;const b=btn(rack,window.DanceCast?.[stem.id]?.name||stem.id,()=>{if(performance.now()>suppressClickUntil)queueVoice(stem.id);});b.dataset.voice=stem.id;b.draggable=true;b.setAttribute('aria-pressed','false');const img=el('img',undefined);img.src='./assets/sprunki-kiss-local/assets/'+window.DanceCast[stem.id].idle;img.alt='';b.prepend(img);b.ondragstart=e=>{e.dataTransfer.setData('text/plain',stem.id);e.dataTransfer.effectAllowed='copy';};let pointer=null;b.onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY};};b.onpointerup=e=>{if(pointer&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>20){const rect=stage.getBoundingClientRect();if(e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom){e.preventDefault();suppressClickUntil=performance.now()+700;placeVoice(stem.id,e.clientX>rect.left+rect.width*.6?'player':'rival');queueVoice(stem.id,true);}}pointer=null;};b.onpointercancel=()=>{pointer=null;};}}
    function placeVoice(id,side){if(!window.DanceCast[id])return;if(side==='player')castOverride.player=id;else {const ids=[...(castOverride.rivals||selected.cast||[])].filter(x=>x!==id);castOverride.rivals=[id,...ids];}picture();}
    async function queueVoice(id,force=false){if(starting&&!running)return;if(!window.DanceCast[id])return;if(!selected?.mix){stopAudio();songSelect.value='mix-sunny';chosen();}if(id==='black'){placeVoice(id,'rival');status.textContent='Black 只展示正常造型，不播放恐怖声音，也不会变换其他角色';return;}const i=selected.mix.findIndex(s=>s.id===id);if(i<0)return;if(!force)placeVoice(id,id==='computer'?'player':'rival');if(!running){pendingVoice=id;begin.click();return;}if(!liveMix)return;const button=rack.querySelector('[data-voice="'+id+'"]'),enabled=force||button?.getAttribute('aria-pressed')!=='true';const at=liveMix.setVoice(i,enabled);if(at===null){status.textContent='歌曲即将结束，重新开始后可加入';return;}button?.setAttribute('aria-pressed',String(enabled));status.textContent=(window.DanceCast[id]?.name||id)+(enabled?'将在下一乐句加入合奏':'将在下一乐句休息');}
    stage.ondragover=e=>{if(selected){e.preventDefault();e.dataTransfer.dropEffect='copy';}};stage.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain'),rect=stage.getBoundingClientRect();placeVoice(id,e.clientX>rect.left+rect.width*.6?'player':'rival');queueVoice(id,true);};
    function addPose(figure,id){if(poseRows[id]===undefined)return;figure.querySelector('img')?.remove();const sprite=el('div',undefined,figure);sprite.className='dance-pose cast-pose';sprite.style.setProperty('--pose-row',poseRows[id]);sprite.setAttribute('role','img');sprite.setAttribute('aria-label',id+'方向动作');figure.prepend(sprite);}
    const poseAnimations=new Map();
    function poseDuration(){return Math.max(280,Math.min(520,60000/(selected?.bpm||100)*.75));}
    function setPose(figure,lane,replay=false){if(!replay&&figure.dataset.pose===String(lane))return;const sprite=figure.querySelector('.dance-pose,img,canvas.dance-original');figure.dataset.poseStart=String(time());poseAnimations.get(figure)?.cancel();poseAnimations.delete(figure);figure.dataset.pose=String(lane);figure.style.setProperty('--pose-x',((lane<0?1:lane)*100/3)+'%');if(lane<0||!sprite||(!customMotion&&sprite.classList.contains('dance-original'))||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
      const peak=['translate(-10px,-2px) rotate(-9deg) scale(1.04,.98)','translate(0,9px) rotate(2deg) scale(1.12,.84)','translate(0,-14px) rotate(-2deg) scale(.91,1.12)','translate(10px,-2px) rotate(9deg) scale(1.04,.98)'][lane];
      const settle=['translate(-4px,0) rotate(-3deg)','translate(0,3px) scale(1.03,.97)','translate(0,-4px) scale(.99,1.03)','translate(4px,0) rotate(3deg)'][lane];
      const animation=sprite.animate([{transform:'translate(0,0) scale(1)',offset:0},{transform:'translate(0,3px) scale(1.025,.965)',offset:.14},{transform:peak,offset:.38},{transform:settle,offset:.73},{transform:'translate(0,0) scale(1)',offset:1}],{duration:poseDuration(),easing:'cubic-bezier(.22,.65,.35,1)',fill:'forwards'});poseAnimations.set(figure,animation);
    }
    function updateScreen(t){const screen=player.querySelector('.dance-screen-caption');if(!screen)return;const words=player.classList.contains('singing')?window.DanceMusic.captionAt(selected.captions,t):'';screen.hidden=!words;if(screen.textContent!==words)screen.textContent=words;}
    const picture=()=>{const lead=castOverride.player||referenceRoles.player||leadCharacter(selected);player.replaceChildren();player.classList.remove('singing');useOriginal(player,lead);setPose(player,-1);player.dataset.character=lead||'partner';rival.replaceChildren();const ids=selected?.reference?[referenceRoles.dad,referenceRoles.gf]:(castOverride.rivals||selected?.cast||[]).filter(id=>id!==lead).slice(0,opponentCount);ids.forEach((id,i)=>{if(!id)return;const figure=el('div',undefined,rival);figure.dataset.role=i===0?'dad':'gf';useOriginal(figure,id);setPose(figure,-1);});};
    let demoTimer=0;
    let ctx,raf=0,active=true,running=false,notes=[],startTime=0,score=0,combo=0,rivalScore=0,nextSound=0,moveUntil=0,rivalBeat=-1,selected=library[0],media=null,mediaURL=null,db=null,starting=false,importing=false,video=null,playSession=0;const arrows=['←','↓','↑','→'];
    const libraryBox=el('details',undefined);libraryBox.className='dance-library';host.prepend(libraryBox);el('summary','更多歌曲 / 本机音频',libraryBox);
    const cards=el('div',undefined);cards.className='dance-song-cards';cards.setAttribute('aria-label','点歌即玩');host.prepend(cards);
    const videoBox=el('div',undefined,host.querySelector('.dance-stage'));videoBox.className='dance-video';videoBox.hidden=true;
    const search=el('input',undefined,libraryBox);search.type='search';search.placeholder='搜索歌名';search.setAttribute('aria-label','搜索歌名');
    const filterLabel=el('label','只看歌名带 SPRUNKI 的歌曲',libraryBox),filter=el('input',undefined,filterLabel);filter.type='checkbox';
    const importLabel=el('label','批量导入歌曲',libraryBox),files=el('input',undefined,importLabel);files.type='file';files.accept='.mp3,.wav,.ogg,.m4a,.aac,.flac,.webm';files.multiple=true;files.disabled=true;
    const libraryStatus=el('p','正在打开本机歌曲库…',libraryBox);libraryStatus.setAttribute('role','status');
    const tempoLabel=el('label','节拍速度 BPM',libraryBox),tempo=el('input',undefined,tempoLabel);tempo.type='number';tempo.min=40;tempo.max=240;tempo.value=120;tempo.setAttribute('aria-label','歌曲节拍速度');
    el('small','导入完整音频后可选歌对战，保存在本机。每首最多 25 MB、15 分钟。导入曲目的箭头按所设节拍生成，可调整 BPM；不是原曲官方谱面。',libraryBox);
    const lyricLabel=el('label','为当前歌曲添加定时歌词（LRC）',libraryBox),lyricFile=el('input',undefined,lyricLabel);lyricFile.type='file';lyricFile.accept='.lrc';lyricFile.onchange=async()=>{const file=lyricFile.files[0],track=selected;if(!file||!track)return;if(file.size>200000){libraryStatus.textContent='歌词文件太大';return;}const cues=window.DanceMusic.parseLyrics(await file.text());if(!cues.length){libraryStatus.textContent='没有找到带时间的歌词';return;}track.captions=cues;const stored=save('lyrics-'+track.id,cues);libraryStatus.textContent=stored?'歌词已保存，会在电脑先生唱歌时显示在屏幕上':'歌词已载入，本机保存失败';lyricFile.value='';};
    const sources=el('details',undefined,libraryBox);sources.className='dance-song-sources';el('summary','找歌曲 · 原曲与作者页面',sources);el('p','这些是歌曲来源链接，需要联网打开。拿到可播放的音频文件后，可用上面的导入按钮加入对战。',sources);
    for(const source of songSources){const link=el('a',source.name+' — '+source.artist,sources);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';}
    const remove=btn(libraryBox,'移除所选导入歌曲',async()=>{if(!selected?.imported||running||starting)return;try{await transaction(['tracks','audio'],'readwrite',tx=>{tx.objectStore('tracks').delete(selected.id);tx.objectStore('audio').delete(selected.id);});library=library.filter(s=>s.id!==selected.id);renderSongs();libraryStatus.textContent='已移除歌曲';}catch{libraryStatus.textContent='移除失败，请重试';}});
    function transaction(stores,mode,action){return new Promise((resolve,reject)=>{if(!db){reject(Error('歌曲库不可用'));return;}const tx=db.transaction(stores,mode);let req;try{req=action(tx);}catch(e){reject(e);return;}tx.oncomplete=()=>resolve(req?.result);tx.onerror=tx.onabort=()=>reject(tx.error||Error('存储失败'));});}
    const request=indexedDB.open('computer-dance-library',1);request.onupgradeneeded=()=>{request.result.createObjectStore('tracks',{keyPath:'id'});request.result.createObjectStore('audio');};request.onsuccess=async()=>{db=request.result;if(!active){db.close();return;}try{const tracks=await transaction(['tracks'],'readonly',tx=>tx.objectStore('tracks').getAll());if(!active)return;library.push(...tracks.map(t=>({...t,captions:read('lyrics-'+t.id,[])})));renderSongs();files.disabled=false;libraryStatus.textContent=tracks.length?`已载入 ${tracks.length} 首导入歌曲`:'两首原曲及正常模式音色随游戏提供；没有视频广告或恐怖曲目。';}catch{libraryStatus.textContent='歌曲库读取失败；练习曲仍可玩。';}};request.onerror=()=>libraryStatus.textContent='本机存储不可用，无法保存导入歌曲。';
    function chosen(){selected=library.find(s=>s.id===songSelect.value);castOverride={};referenceRoles={...(selected?.initial||{})};referenceEvent=referenceNote=0;renderRack();opponents.disabled=!!selected?.reference;host.style.setProperty('--dance-beat',(60/(selected?.bpm||100))+'s');if(!running&&!starting)picture();tempo.value=selected?.bpm||120;tempo.disabled=!selected?.imported;remove.disabled=!selected?.imported;begin.disabled=!selected||starting;if(running||starting)lock(true);}
    function renderSongs(){const old=songSelect.value;cards.replaceChildren();for(const track of library.filter(s=>s.reference||s.video||s.mix)){const card=btn(cards,track.name+' · '+track.artist,()=>{stopAudio();search.value='';filter.checked=false;renderSongs();songSelect.value=track.id;chosen();begin.click();});card.dataset.song=track.id;} songSelect.replaceChildren();for(const s of library.filter(s=>matchesSong(s,search.value,filter.checked))){const o=el('option',`${s.name} · ${s.reference?'原曲 · 原谱面':s.video?'在线原曲':s.mix?'自由合奏':s.imported?'原文件':'自制练习'} · ${Math.round(s.bpm*100)/100} BPM`,songSelect);o.value=s.id;}if([...songSelect.options].some(o=>o.value===old))songSelect.value=old;chosen();if(!selected){status.textContent='没有匹配歌曲。可清除筛选，或导入带 SPRUNKI 名字的音频文件。';}else if(!running&&!video&&!starting)status.textContent=`已选择：${selected.name} · 点上方歌名即可开始`;}
    search.oninput=filter.onchange=renderSongs;songSelect.onchange=()=>{stopAudio();chosen();begin.click();};
    tempo.onchange=async()=>{if(!selected?.imported)return;selected.bpm=Math.max(40,Math.min(240,Number(tempo.value)||120));tempo.value=selected.bpm;try{await transaction(['tracks'],'readwrite',tx=>tx.objectStore('tracks').put(selected));renderSongs();}catch{libraryStatus.textContent='节拍已更改，但保存失败。';}};
    function durationOf(file){return new Promise((resolve,reject)=>{const a=new Audio(),url=URL.createObjectURL(file);const timer=setTimeout(()=>finish(Error('读取超时')),10000);function finish(error){clearTimeout(timer);const duration=a.duration;a.removeAttribute('src');a.load();URL.revokeObjectURL(url);error?reject(error):resolve(duration);}a.onloadedmetadata=()=>finish();a.onerror=()=>finish(Error('格式不能播放'));a.preload='metadata';a.src=url;});}
    files.onchange=async()=>{if(running||starting)return;importing=true;files.disabled=true;const batch=[...files.files];let added=0;const failures=[];for(const file of batch){if(!active)break;if(!audioFileAllowed(file)){failures.push(file.name+'：格式不支持或超过 25 MB');continue;}const id=`file-${file.name}-${file.size}-${file.lastModified}`;if(library.some(s=>s.id===id))continue;try{const duration=await durationOf(file);if(!active)break;if(!Number.isFinite(duration)||duration<4||duration>900)throw Error('时长需为 4 秒至 15 分钟');const track={id,name:file.name.replace(/\.[^.]+$/,''),duration,bpm:120,imported:true};await transaction(['tracks','audio'],'readwrite',tx=>{tx.objectStore('tracks').put(track);tx.objectStore('audio').put(file,id);});library.push(track);added++;libraryStatus.textContent=`已导入 ${added} 首…`;}catch(e){failures.push(file.name+'：'+e.message);}}importing=false;if(active){files.value='';files.disabled=running||starting;renderSongs();libraryStatus.textContent=`已添加 ${added} 首。${failures.join('；')}`;}};
    function lock(value){files.disabled=value||importing||!db;songSelect.disabled=starting;search.disabled=filter.disabled=value;tempo.disabled=value||!selected?.imported;remove.disabled=value||!selected?.imported;}
    function stopAudio(){liveMix?.stop();liveMix=null;rack.querySelectorAll('[data-voice]').forEach(b=>{b.dataset.singing='false';b.setAttribute('aria-pressed','false');});clearInterval(demoTimer);demoTimer=0;poseAnimations.forEach(a=>a.cancel());poseAnimations.clear();playSession++;running=false;resume.hidden=true;if(video){video.destroy();video=null;}videoBox.replaceChildren();videoBox.hidden=true;if(media){media.onended=media.onerror=null;media.pause();media.removeAttribute('src');media.load();media=null;}if(mediaURL){URL.revokeObjectURL(mediaURL);mediaURL=null;}if(ctx){ctx.close();ctx=null;}rival.style.transform='';player.classList.remove('singing');setPose(player,-1);updateScreen(0);rival.querySelectorAll(':scope > div').forEach(f=>{f.classList.remove('singing');f.style.transform='';setPose(f,-1);f.dataset.poseUntil='0';});lock(false);}
    function finish(){updateBattle(selected?.duration||0);stopAudio();status.textContent=`${score>=rivalScore?'你获胜了！':'对手获胜，再来一次！'} 你 ${score} : 对手 ${rivalScore}`;}
    const begin=btn(host.querySelector('.dance-toolbar'),'开始对战',async()=>{if(!selected||starting)return;starting=true;host.classList.add('game-is-loading');begin.disabled=true;stopAudio();const session=playSession;retry.hidden=true;resume.hidden=true;lock(true);cards.querySelectorAll('button').forEach(b=>b.disabled=true);try{status.textContent='正在准备：'+selected.name;notes=chart(selected);if(selected.mix)notes=notes.filter(n=>[[16,48],[64,112]].some(([a,b])=>n.time>=2+a*60/selected.bpm+1.8&&n.time<=2+b*60/selected.bpm));score=combo=rivalScore=nextSound=0;rivalBeat=-1;referenceRoles={...(selected.initial||{})};referenceEvent=referenceNote=0;picture();updateBattle();await window.DanceReference.prepare([player.dataset.character,...Array.from(rival.children,f=>f.dataset.character)]);if(!active||session!==playSession)return;if(selected.video){videoBox.hidden=false;const credit=el('p',selected.name+' — '+selected.artist+' · 在线原曲 · 练习谱面 / 舞台搭档',videoBox);const slot=el('div',undefined,videoBox);status.textContent='正在连接原曲…';const openedVideo=await window.DanceMusic.open(slot,selected,{
      loading:message=>{if(active&&session===playSession){running=false;status.textContent=message;}},
      state:(state,p)=>{if(!active||session!==playSession)return;resume.hidden=state===1;if(state===1){const duration=p.getDuration();if(duration>3&&notes.length!==chart({...selected,duration}).length)notes=chart({...selected,duration});running=true;status.textContent='正在播放：'+selected.name+' · 接住白线上的箭头';}else if(state===0)finish();else{running=false;status.textContent=state===3?'音乐缓冲中…':'点击原曲播放器的播放按钮继续';}},
      blocked:()=>{if(active&&session===playSession){running=false;resume.hidden=false;status.textContent='浏览器暂停了自动播放，请点“播放声音”';}},
      error:message=>{if(session===playSession){stopAudio();retry.hidden=false;status.textContent=message;}}
    });if(!active||session!==playSession){openedVideo?.destroy();return;}video=openedVideo;begin.textContent='重新开始';return;
    }else if(selected.mix){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const schedule=await window.DanceMusic.prepareLiveMix(ctx,selected);if(!active||session!==playSession)return;startTime=ctx.currentTime+.1;liveMix=schedule(startTime);videoBox.hidden=true;}else if(selected.audioFile){media=new Audio(selected.audioFile);media.onended=finish;media.onerror=()=>{stopAudio();retry.hidden=false;status.textContent='本机歌曲读取失败，请重试';};await media.play();if(!active||session!==playSession)return;videoBox.hidden=true;}else if(selected.mix){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const schedule=await window.DanceMusic.prepareMix(ctx,selected);if(!active||session!==playSession)return;startTime=ctx.currentTime;schedule(startTime);videoBox.hidden=true;}else if(selected.imported){const blob=await transaction(['audio'],'readonly',tx=>tx.objectStore('audio').get(selected.id));if(!active)return;if(!blob)throw Error('音频文件缺失');mediaURL=URL.createObjectURL(blob);media=new Audio(mediaURL);media.onended=finish;media.onerror=()=>{stopAudio();status.textContent='这首歌无法播放，请重新导入可播放的音频';};await media.play();}else{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();startTime=ctx.currentTime;}if(!active){stopAudio();return;}running=true;if(pendingVoice){const id=pendingVoice;pendingVoice=null;queueVoice(id,true);}begin.textContent='重新开始';status.textContent=`正在播放：${selected.name}${selected.mix?' · 多角色离线合奏 / 练习谱面':''} · 用方向键或下方箭头接拍`;}catch(e){if(active&&session===playSession){stopAudio();retry.hidden=false;status.textContent='歌曲未能播放：'+e.message;}}finally{host.classList.remove('game-is-loading');starting=false;begin.disabled=!selected;songSelect.disabled=false;cards.querySelectorAll('button').forEach(b=>b.disabled=false);}});
    const retry=btn(host.querySelector('.dance-toolbar'),'重试原曲',()=>begin.click());retry.hidden=true;const resume=btn(host.querySelector('.dance-toolbar'),'播放声音',()=>video?.playVideo());resume.hidden=true;
    btn(host.querySelector('.dance-toolbar'),'停止 / 换歌',()=>{if(starting)return;stopAudio();status.textContent='已停止，可以重新选择歌曲';});
    const opponentsLabel=el('label','对手 ',host.querySelector('.dance-toolbar')),opponents=el('select',undefined,opponentsLabel);opponents.setAttribute('aria-label','对手人数');for(const n of [1,2]){const o=el('option',n+' 位',opponents);o.value=n;}opponents.value=2;opponents.onchange=()=>{opponentCount=Number(opponents.value);if(!selected?.reference)picture();};
    const motionLabel=el('label','动作 ',host.querySelector('.dance-toolbar')),motion=el('select',undefined,motionLabel);motion.setAttribute('aria-label','角色动作模式');for(const [value,name] of [['original','原版角色动作'],['custom','自创方向动作']]){const o=el('option',name,motion);o.value=value;}motion.onchange=()=>{customMotion=motion.value==='custom';host.classList.toggle('dance-custom-motion',customMotion);};
    btn(host.querySelector('.dance-toolbar'),'四方向动作演示',()=>{if(starting)return;stopAudio();customMotion=true;motion.value='custom';host.classList.add('dance-custom-motion');let lane=0;const tick=()=>{if(!active)return;setPose(player,lane,true);moveUntil=performance.now()+poseDuration();rival.querySelectorAll(':scope > div').forEach(f=>{setPose(f,lane,true);f.dataset.poseUntil=String(moveUntil);});status.textContent=['向左：侧头探出，再回弹','向下：压低身体，再弹起','向上：抬头伸展，再落回','向右：侧向右边，再回弹'][lane]+' · 点停止结束演示';lane=(lane+1)%4;};tick();demoTimer=setInterval(tick,Math.max(720,poseDuration()+220));});renderSongs();
    function time(){return video?video.getCurrentTime():media?media.currentTime:ctx?Math.max(0,ctx.currentTime-(ctx.outputLatency||0)-startTime):0;}
    function drawArrow(lane,x,y,size,color){g.save();g.translate(x,y);g.rotate([Math.PI,Math.PI/2,-Math.PI/2,0][lane]);g.beginPath();const points=[[-.46,-.19],[.02,-.19],[.02,-.47],[.49,0],[.02,.47],[.02,.19],[-.46,.19]];points.forEach(([a,b],i)=>i?g.lineTo(a*size,b*size):g.moveTo(a*size,b*size));g.closePath();g.fillStyle=color;g.strokeStyle='#10142c';g.lineWidth=Math.max(4,size*.12);g.lineJoin='round';g.stroke();g.fill();g.save();g.translate(-size*.025,-size*.025);g.scale(.77,.77);g.strokeStyle='#ffffffb8';g.lineWidth=Math.max(1.5,size*.035);g.stroke();g.restore();g.restore();}
    function hit(lane){if(!running)return;const t=time(),n=notes.find(n=>!n.done&&n.lane===lane&&Math.abs(n.time-t)<=.2);const points=n?grade(n.time-t):0;if(n){n.done=true;score+=points;combo++;}else combo=0;setPose(player,lane,true);moveUntil=performance.now()+poseDuration();const target=host.querySelectorAll('.dance-targets button')[lane];target.dataset.feedback=points?'hit':'miss';target.dataset.until=String(moveUntil);status.textContent=`${points===100?'完美':points?'接住了':'没接到'} · 得分 ${score} · 连击 ${combo} · 对手 ${rivalScore}`;}
    arrows.forEach((a,i)=>{const b=btn(host.querySelector('.dance-targets'),a,()=>hit(i));b.setAttribute('aria-label',['左','下','上','右'][i]+'方向落点');b.innerHTML='<svg viewBox="0 0 100 100" aria-hidden="true"><g transform="translate(50 50) rotate('+[180,90,-90,0][i]+')"><path d="M -40 -17 H 1 V -40 L 43 0 L 1 40 V 17 H -40 Z"/></g></svg>';});const key=e=>{const i=['ArrowLeft','ArrowDown','ArrowUp','ArrowRight'].indexOf(e.key);if(i>=0&&!e.repeat&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();hit(i);}};document.addEventListener('keydown',key);
    function frame(){if(!active)return;raf=requestAnimationFrame(frame);const w=Math.max(120,Math.floor(canvas.clientWidth)),h=Math.max(110,Math.floor(canvas.clientHeight));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}g.clearRect(0,0,w,h);const line=h*.8;g.strokeStyle='#fff';g.beginPath();g.moveTo(0,line);g.lineTo(w,line);g.stroke();g.font=Math.max(15,w/8)+'px sans-serif';g.textAlign='center';const colors=['#c66bea','#43dced','#78e65a','#ff626e'];const now=performance.now();if(now>moveUntil)setPose(player,-1);host.querySelectorAll('.dance-targets button[data-feedback]').forEach(b=>{if(now>Number(b.dataset.until))delete b.dataset.feedback;});rival.querySelectorAll(':scope > div').forEach(f=>{if(now>Number(f.dataset.poseUntil||0))setPose(f,-1);});if(!running){animateOriginal(player,0,false);rival.querySelectorAll(':scope > div').forEach(f=>animateOriginal(f,0,false));return;}const t=time();referenceFrame(t);
      // Schedule music ahead against the audio clock, not animation-frame timing.
      while(!selected.reference&&!selected.video&&!selected.imported&&!selected.mix&&nextSound<notes.length&&notes[nextSound].time<t+.18){const i=nextSound++,n=notes[i],when=startTime+n.time;if(when>=ctx.currentTime){sound(ctx,220*2**(selected.scale[i%8]/12),when,.24,'triangle');sound(ctx,i%4===0?65:110,when,.1,'sine',.12);if(i%2===0)sound(ctx,880,when,.035,'square',.018);}}
      const voices=selected.mix?(liveMix?.voicesAt(t)||[]):[];
      if(selected.mix){const singing=f=>voices.some(i=>selected.mix[i].id===f.dataset.character);rival.querySelectorAll(':scope > div').forEach(f=>f.classList.toggle('singing',singing(f)));player.classList.toggle('singing',singing(player));rack.querySelectorAll('[data-voice]').forEach(b=>{b.dataset.singing=String(voices.some(i=>selected.mix[i].id===b.dataset.voice));});}
      animateOriginal(player,t,player.classList.contains('singing'));rival.querySelectorAll(':scope > div').forEach(f=>animateOriginal(f,t,f.classList.contains('singing')));
      if(selected.vocalWindows)player.classList.toggle('singing',selected.vocalWindows.some(([from,to])=>t>=from&&t<to));
      const beat=Math.floor(Math.max(0,t-2)/(60/selected.bpm));if(!selected.reference&&beat!==rivalBeat){rivalBeat=beat;rival.querySelectorAll(':scope > div').forEach((f,i)=>{if(f.classList.contains('singing')||!selected.mix){setPose(f,(beat+i)%4,true);f.dataset.poseUntil=String(now+poseDuration());}else setPose(f,-1);});}updateScreen(t);rivalScore=notes.filter((n,i)=>n.time<t&&i%(opponentCount===2?5:3)!==0).length*60;updateBattle(t);
      notes.forEach(n=>{if(!n.done&&t>n.time+.2){n.done=true;combo=0;}if(!n.done){const y=line-(n.time-t)*(line/1.8);if(y>-25&&y<h){drawArrow(n.lane,(n.lane+.5)*w/4,y,Math.min(64,w/4*.76),colors[n.lane]);}}});
      if(!selected.video&&!selected.imported&&!media&&t>(selected.mix?selected.duration:notes[notes.length-1].time+1))finish();
    }frame();return()=>{active=false;stopAudio();cancelAnimationFrame(raf);document.removeEventListener('keydown',key);db?.close();};
  }
  function blocks(host) { return window.VoxelWorld.mount(host); }
  window.ComputerApps={catalog,mount};
})();
