/* Runnable, local applications. Every mount returns a cleanup function. */
(() => {
  const catalog = {calculator:['算','计算器'],notes:['记','便签本'],tasks:['单','待办清单'],memory:['牌','记忆翻牌'],piano:['琴','小钢琴'],videos:['视','视频'],characters:['角','角色介绍'],dance:['舞','节奏音乐跳舞游戏'],blocks3d:['立','我的世界 3D']};
  const characterProfile=(group,sound,color,description)=>({age:'未公开',birthday:'未公开',group,sound,color,description});
  const characterProfiles={
    oren:characterProfile('节拍组','基础鼓点','橙色','橙色节拍手，负责稳定的基础节奏。'),raddy:characterProfile('节拍组','强劲鼓点','红色','红色鼓手，声音有力而直接。'),clukr:characterProfile('节拍组','金属镲片','银色','头顶转盘的银色演奏家。'),funbot:characterProfile('节拍组','机械节拍','银灰色','快乐机器人，会用机械节拍带动大家。'),vineria:characterProfile('节拍组','沙锤节奏','绿色','绿色藤蔓歌手，声音轻快。'),
    gray:characterProfile('效果组','低音效果','灰色','安静的灰色低音角色。'),brud:characterProfile('效果组','桶帽打击声','棕色','棕色桶帽角色，带来有趣的节拍。'),garnold:characterProfile('效果组','电子效果','金色','金色护目镜演奏家，是电脑先生的朋友。'),lime:characterProfile('效果组','快速效果音','青柠色','活泼的青柠角色，动作变化很快。'),sky:characterProfile('效果组','明亮效果音','天蓝色','蓝色小熊耳角色，音色明亮。'),
    mr_sun:characterProfile('旋律组','温暖钢琴旋律','黄色','太阳公公，用温暖的旋律照亮舞台。'),durple:characterProfile('旋律组','悠长管乐','紫色','紫色长角歌手，擅长悠长的声音。'),mr_tree:characterProfile('旋律组','厚实低音','棕绿双色','大树先生，负责厚实的低音。'),simon:characterProfile('旋律组','明亮主旋律','黄色','黄色天线歌手，是节奏对战里的主唱之一。'),tunner:characterProfile('旋律组','口哨旋律','棕褐色','棕色宽檐帽角色，吹出清楚的旋律。'),
    computer:characterProfile('人声组','电子人声','灰黑色','电脑先生，黑色屏幕会跟着歌词变化。'),wenda:characterProfile('人声组','清亮人声','白色','白色猫耳歌手，声音清亮。'),pinki:characterProfile('人声组','轻快人声','粉色','粉色蝴蝶结歌手，节奏轻快。'),jevin:characterProfile('人声组','低沉人声','深蓝色','深蓝斗篷歌手，声音沉稳。'),black:characterProfile('人声组','普通阶段无独立声音','黑色','Black 的正常造型；角色介绍不播放恐怖内容。')
  };
  Object.assign(catalog,typeof module!=="undefined"?require("./arcade-games.js").catalog:window.ArcadeGames?.catalog);
  const songs = [{name:'芯片起舞',bpm:96,scale:[0,4,7,12,7,4,2,7]},{name:'霓虹对决',bpm:120,scale:[0,3,7,10,12,10,7,3]},{name:'月光律动',bpm:84,scale:[0,5,9,12,9,7,5,2]},{name:'像素冲刺',bpm:140,scale:[0,7,12,7,3,10,15,10]},{name:'彩虹派对',bpm:110,scale:[0,2,4,7,9,7,4,2]}];
  const chart = song => {if(song.reference)return song.notes.filter(n=>n.hit??n.side==='player').map(n=>({...n,done:false}));const bpm=Math.max(40,Math.min(240,Number(song.bpm)||120)),length=song.duration?Math.max(0,Math.floor((Math.min(900,song.duration)-3)*bpm/60)+1):64;return Array.from({length},(_,i)=>({time:2+i*60/bpm,lane:(i*3+Math.floor(i/4))%4,done:false})).filter(n=>!song.vocalWindows||song.vocalWindows.some(([from,to])=>n.time>=from+1.8&&n.time<=to));};
  const battleChart = song => {
    if(song.reference)return {player:chart(song),opponent:song.notes.filter(n=>!(n.hit??n.side==='player')).map(n=>({...n,done:false}))};
    const all=chart(song),beat=60/(song.bpm||120);
    return {player:all.filter(n=>Math.floor((n.time-2)/beat/4)%2===1),opponent:all.filter(n=>Math.floor((n.time-2)/beat/4)%2===0)};
  };
  const soloChart=song=>song?.reference?song.notes.filter(n=>n.hit===true).map(n=>({...n,done:false})):chart(song);
  const notesForMode=(song,mode)=>mode==='watch'?[]:soloChart(song);
  const singAnimationFor=(available,lane)=>{const wanted=['singLEFT','singDOWN','singUP','singRIGHT'][lane];return available.includes(wanted)?wanted:available.find(name=>name.startsWith('sing'))||'idle';};
  const performanceHold=(side,character,watching,hold=0)=>{const minimum=watching?1.05:(side==='player'&&character==='simon'?0.85:0.68);return Math.max(hold,minimum);};
  const orientedLane=(side,lane)=>side==='player'&&lane%3===0?3-lane:lane;
  const characterFrameDuration=frameCount=>Math.max(220,Math.min(480,Math.round(4800/Math.max(1,frameCount))));
  const NOTE_TRAVEL_SECONDS=2.2;
  const BATTLE_GRACE_MS=5000;
  const noteTravelY=(noteTime,now,start,target)=>{const remaining=Math.max(0,Math.min(NOTE_TRAVEL_SECONDS,noteTime-now));return start+(target-start)*(1-remaining/NOTE_TRAVEL_SECONDS);};
  const noteTravelBounds=(side,height,size,friendLikeYou=false)=>friendLikeYou?{start:height+size*.5,target:height*.17}:side==='player'?{start:-size*.5,target:height*.83}:{start:height+size*.5,target:height*.17};
  const stageSunVisible=ids=>!ids.includes('mr_sun');
  const audioFileAllowed=file=>/\.(mp3|wav|ogg|m4a|aac|flac|webm)$/i.test(file.name)&&file.size>0&&file.size<=25*1024*1024;
  const matchesSong=(song,query,sprunkiOnly=false)=>(!sprunkiOnly||/sprunki/i.test(song.name))&&song.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  const leadCharacter=song=>song?.lead||(song?.mix?.some(stem=>stem.id==='computer')||song?.vocalWindows?.length?'computer':song?.cast?.[0]||null);
  const grade = delta => Math.abs(delta)<=.1 ? 100 : Math.abs(delta)<=.28 ? 60 : 0;
  const songSources=[{name:'Colorful Bunch · 原作者模组与曲目',artist:'Just_Camilo',url:'https://gamebanana.com/mods/585004'},
    {name:'Friend Like You · FNF 演出参考',artist:'Neonight',url:'https://www.youtube.com/watch?v=_bwDYOzbkBY'}
  ];
  const offlineVideoLibrary=[
    {name:'Friend Like You 离线舞台',cast:['mr_tree','computer','black'],duration:150,bpm:120,theme:'friend',soundtrack:'./assets/dance-audio/friend-like-you-safe.wav'},
    {name:'电脑先生之歌',cast:['computer'],duration:38,bpm:120,theme:'computer'},
    {name:'草地大合奏',cast:['oren','raddy','clukr','funbot','vineria'],duration:42,bpm:112,theme:'meadow'},
    {name:'太阳公公音乐会',cast:['mr_sun','mr_tree','simon','pinki'],duration:40,bpm:104,theme:'sunny'},
    {name:'快乐机器人节拍',cast:['funbot','garnold','clukr','computer'],duration:36,bpm:124,theme:'robot'},
    {name:'彩虹朋友派对',cast:['wenda','pinki','jevin','durple','sky'],duration:44,bpm:110,theme:'rainbow'},
    {name:'树林里的歌',cast:['mr_tree','vineria','gray','tunner'],duration:39,bpm:96,theme:'forest'},
    {name:'双人节奏表演',cast:['oren','simon'],duration:34,bpm:120,theme:'duet'},
    {name:'二十人离线合唱',cast:['oren','raddy','clukr','funbot','vineria','gray','brud','garnold','lime','sky','mr_sun','durple','mr_tree','simon','tunner','computer','wenda','pinki','jevin','black'],duration:60,bpm:120,theme:'finale'}
  ];
  if(typeof module!=='undefined') { module.exports={catalog,characterProfiles,songs,chart,battleChart,soloChart,notesForMode,singAnimationFor,performanceHold,orientedLane,characterFrameDuration,stageSunVisible,noteTravelY,noteTravelBounds,grade,audioFileAllowed,matchesSong,songSources,leadCharacter}; return; }
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('apps-'+key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem('apps-'+key,JSON.stringify(value));return true;}catch{return false;}};
  const el=(tag,text,parent)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n;};
  const btn=(parent,text,fn)=>{const b=el('button',text,parent);b.type='button';b.onclick=fn;return b;};
  function sound(ctx,freq,start,duration=.16,type='sine',volume=.08){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,start);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(ctx.destination);o.onended=()=>{o.disconnect();g.disconnect();};o.start(start);o.stop(start+duration);}
  function mount(id,host){host.classList.add('extra-app');
    if(window.ArcadeGames?.catalog[id])return window.ArcadeGames.mount(id,host);
    if(id==='videos')return videos(host); if(id==='characters')return characters(host); if(id==='dance')return dance(host); if(id==='blocks3d')return blocks(host);
    if(id==='calculator'){
      const input=el('input',undefined,host);input.type='text';input.placeholder='输入两个数字，例如 12 × 3';input.setAttribute('aria-label','计算式');const out=el('output','',host);
      const calc=()=>{const m=input.value.match(/^\s*(-?\d+(?:\.\d+)?)\s*([+\-*/×÷])\s*(-?\d+(?:\.\d+)?)\s*$/);if(!m){out.textContent='请输入 数字 运算符 数字';return;}const a=+m[1],b=+m[3];const result={'+':()=>a+b,'-':()=>a-b,'*':()=>a*b,'×':()=>a*b,'/':()=>a/b,'÷':()=>a/b}[m[2]]();out.textContent=Number.isFinite(result)?String(result):'不能除以零';};btn(host,'计算',calc);input.onkeydown=e=>{if(e.key==='Enter')calc();};
    }else if(id==='notes'){
      const area=el('textarea',undefined,host);area.setAttribute('aria-label','便签内容');area.value=String(read('notes',''));area.placeholder='写下想记住的事情…';const status=el('small','自动保存在本机',host);area.oninput=()=>status.textContent=save('notes',area.value)?'已保存':'保存失败，请复制文字留存';
    }else if(id==='tasks'){
      const input=el('input',undefined,host);input.placeholder='新的待办';input.setAttribute('aria-label','新的待办');const list=el('div',undefined,host);let items=read('tasks',[]);if(!Array.isArray(items))items=[];items=items.filter(x=>x&&typeof x.text==='string');
      const render=()=>{list.replaceChildren();items.forEach((item,i)=>{const row=el('label',undefined,list),check=el('input',undefined,row);check.type='checkbox';check.checked=!!item.done;el('span',item.text,row);check.onchange=()=>{item.done=check.checked;save('tasks',items);};btn(row,'删除',()=>{items.splice(i,1);save('tasks',items);render();});});};const add=()=>{if(!input.value.trim())return;items.push({text:input.value.trim(),done:false});input.value='';save('tasks',items);render();};btn(host,'添加待办',add);input.onkeydown=e=>{if(e.key==='Enter')add();};render();
    }else if(id==='memory'){
      const info=el('p','找到所有相同图案',host),grid=el('div',undefined,host);grid.className='memory-grid';let timer=0,first=null,locked=false,matches=0,moves=0;
      const start=()=>{clearTimeout(timer);first=null;locked=false;matches=0;moves=0;info.textContent='找到所有相同图案';grid.replaceChildren();const cards=['🌈','🎵','💻','🌟','🌈','🎵','💻','🌟'];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}cards.forEach(symbol=>{const b=btn(grid,'?',()=>{if(locked||b.disabled||b===first)return;b.textContent=symbol;if(!first){first=b;return;}moves++;if(first.textContent===symbol){b.disabled=first.disabled=true;matches++;first=null;info.textContent=matches===4?`全部找到！用了 ${moves} 次`:`已找到 ${matches}/4 对`;}else{locked=true;timer=setTimeout(()=>{first.textContent=b.textContent='?';first=null;locked=false;},700);}});});};btn(host,'重新洗牌',start);start();return()=>clearTimeout(timer);
    }else if(id==='piano'){
      el('p','点击琴键演奏',host);let ctx;const keys=el('div',undefined,host);keys.className='piano-keys';['Do','Re','Mi','Fa','Sol','La','Si','Do↑'].forEach((name,i)=>btn(keys,name,async()=>{try{ctx??=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();sound(ctx,261.63*2**([0,2,4,5,7,9,11,12][i]/12),ctx.currentTime,.6,'triangle');}catch{keys.title='浏览器没有开启声音';}}));return()=>{if(ctx)ctx.close();};
    }
    return()=>{};
  }

  function videos(host){
    host.classList.add('offline-video-app');
    const heading=el('h2','节奏盒子视频',host),help=el('p','联网时看 YouTube 原视频；断网时播放电脑先生里保存的本地演出。',host),tabs=el('div',undefined,host),onlineTab=btn(tabs,'在线视频',()=>setMode('online')),offlineTab=btn(tabs,'离线演出',()=>setMode('offline')),online=el('section',undefined,host),onlineFrame=el('iframe',undefined,online),onlineLink=el('a','在 YouTube 打开 Friend Like You 原视频',online),player=el('section',undefined,host),stage=el('div',undefined,player),caption=el('strong','',player),controls=el('div',undefined,player),toggle=btn(controls,'播放',()=>playing?pause():play()),restart=btn(controls,'从头播放',()=>play(true)),progress=el('progress',undefined,controls),grid=el('div',undefined,host);
    heading.className='offline-video-title';help.className='offline-video-help';player.className='offline-video-player';stage.className='offline-video-stage';caption.className='offline-video-caption';controls.className='offline-video-controls';progress.max=1;progress.value=0;progress.setAttribute('aria-label','视频进度');grid.className='offline-video-grid';grid.setAttribute('aria-label','离线节奏盒子视频');
    tabs.className='video-mode-tabs';online.className='online-video-panel';onlineFrame.title='Friend Like You FNF 原视频';onlineFrame.loading='eager';onlineFrame.allow='autoplay; encrypted-media; picture-in-picture';onlineFrame.allowFullscreen=true;onlineLink.href='https://www.youtube.com/watch?v=_bwDYOzbkBY';onlineLink.target='_blank';onlineLink.rel='noopener noreferrer';
    let selected=offlineVideoLibrary[0],playing=false,startAt=0,elapsed=0,raf=0,audios=[];
    const asset=name=>'./assets/sprunki-kiss-local/assets/'+name;
    const framesFor=(video,id)=>{const special={mr_tree:'mr-tree',computer:'computer',black:'black'}[id];return video.theme==='friend'&&special?['idle','left','down','up','right'].map(pose=>`./assets/friend-like-you/${special}-${pose}.png`):[window.DanceCast[id].idle,...(window.DanceCast[id].frames||[])].map(asset);};
    function stopSounds(){audios.forEach(audio=>{audio.pause();audio.currentTime=0;});audios=[];}
    function draw(t=0){
      stage.dataset.theme=selected.theme;stage.dataset.phase=selected.theme==='friend'&&t>=55?'black':'day';stage.replaceChildren();caption.textContent=selected.name;
      const visible=selected.cast;
      visible.forEach((id,index)=>{const art=window.DanceCast?.[id];if(!art)return;const figure=el('figure',undefined,stage),img=el('img',undefined,figure),frames=framesFor(selected,id);figure.dataset.videoCharacter=id;img.alt=art.name;img.src=frames[index%frames.length];el('figcaption',art.name,figure);});
    }
    function frame(now){if(!playing)return;elapsed=(now-startAt)/1000;if(elapsed>=selected.duration){startAt=now;elapsed=0;}progress.value=elapsed/selected.duration;stage.dataset.phase=selected.theme==='friend'&&elapsed>=55?'black':'day';const beat=Math.floor(elapsed*(selected.bpm||120)/60*2);const figures=stage.querySelectorAll('[data-video-character]');figures.forEach((figure,index)=>{const frames=framesFor(selected,figure.dataset.videoCharacter),frameIndex=(beat+index)%frames.length,img=figure.querySelector('img'),src=frames[frameIndex];if(img.getAttribute('src')!==src)img.src=src;figure.classList.toggle('video-singing',(beat+index)%4!==0);});raf=requestAnimationFrame(frame);}
    function play(fromStart=false){
      if(fromStart)elapsed=0;stopSounds();playing=true;toggle.textContent='暂停';startAt=performance.now()-elapsed*1000;
      if(selected.soundtrack){const audio=new Audio(selected.soundtrack);audio.loop=true;audio.volume=.72;audio.currentTime=elapsed;audio.play().catch(()=>{});audios.push(audio);}else selected.cast.forEach(id=>{const art=window.DanceCast?.[id];if(!art?.audio||art.silent)return;const audio=new Audio(art.audio.includes('/')?art.audio:`./assets/dance-audio/normal/${id}.wav`);audio.loop=true;audio.volume=selected.cast.length>8?.1:.2;audio.currentTime=elapsed;audio.play().catch(()=>{});audios.push(audio);});
      cancelAnimationFrame(raf);raf=requestAnimationFrame(frame);
    }
    function pause(){playing=false;toggle.textContent='继续播放';cancelAnimationFrame(raf);stopSounds();}
    function setMode(mode){const showOnline=mode==='online';pause();online.hidden=!showOnline;player.hidden=grid.hidden=showOnline;onlineTab.setAttribute('aria-pressed',String(showOnline));offlineTab.setAttribute('aria-pressed',String(!showOnline));if(showOnline){onlineFrame.src='https://www.youtube-nocookie.com/embed/_bwDYOzbkBY?rel=0&playsinline=1';}else{onlineFrame.removeAttribute('src');draw();}}
    offlineVideoLibrary.forEach((video,index)=>{const card=btn(grid,'',()=>{pause();selected=video;elapsed=0;draw();grid.querySelectorAll('button').forEach(button=>button.setAttribute('aria-pressed',String(button===card)));play(true);});card.className='offline-video-card';card.setAttribute('aria-pressed',String(index===0));const preview=el('span',undefined,card);preview.className='offline-video-thumb';video.cast.slice(0,4).forEach(id=>{const img=el('img',undefined,preview),art=window.DanceCast?.[id];if(art){img.src=asset(art.idle);img.alt='';}});el('strong',video.name,card);el('small',`${video.duration} 秒 · 本机视频`,card);});
    setMode(navigator.onLine?'online':'offline');
    return()=>{playing=false;cancelAnimationFrame(raf);stopSounds();onlineFrame.removeAttribute('src');};
  }

  function characters(host){
    host.classList.add('character-guide-app');
    const ids=Object.keys(window.DanceCast||{}),title=el('h2','节奏盒子角色介绍',host),viewer=el('section',undefined,host),prev=btn(viewer,'‹',()=>show(index-1)),card=el('article',undefined,viewer),next=btn(viewer,'›',()=>show(index+1)),image=el('img',undefined,card),name=el('h3','',card),description=el('p','',card),facts=el('dl',undefined,card),sourceNote=el('small','年龄资料没有统一的官方数字；没有可靠资料的项目会标成“未公开”。',card),soundButton=btn(card,'播放角色声音',()=>playSound());
    facts.className='character-guide-facts';sourceNote.className='character-guide-source-note';
    prev.className='character-guide-prev';next.className='character-guide-next';soundButton.className='character-guide-sound';viewer.className='character-guide-viewer';image.alt='';let index=0,audio=null,frameTimer=0,frame=0;
    const asset=file=>'./assets/sprunki-kiss-local/assets/'+file;
    function stop(){clearInterval(frameTimer);frameTimer=0;if(audio){audio.pause();audio.currentTime=0;audio=null;}}
    function animate(art){clearInterval(frameTimer);frame=0;const frames=art.frames?.length?art.frames:[art.idle],frameMs=characterFrameDuration(frames.length);frameTimer=setInterval(()=>{if(image.isConnected)image.src=asset(frames[frame++%frames.length]);},frameMs);}
    function playSound(){stop();const id=ids[index],art=window.DanceCast[id];animate(art);if(art.audio&&!art.silent){audio=new Audio(art.audio.includes('/')?art.audio:`./assets/dance-audio/normal/${id}.wav`);audio.volume=Math.min(.7,Math.max(.25,(art.gain||.17)*2.4));audio.play().catch(()=>{});audio.addEventListener('ended',()=>{clearInterval(frameTimer);image.src=asset(art.idle);},{once:true});}}
    function show(nextIndex){stop();index=(nextIndex+ids.length)%ids.length;const id=ids[index],art=window.DanceCast[id],profile=characterProfiles[id]||characterProfile('未公开','未公开','未公开','正常模式角色。');image.src=asset(art.idle);image.alt=art.name;name.textContent=`${index+1} / ${ids.length} · ${art.name}`;description.textContent=profile.description;facts.replaceChildren();for(const [label,value] of [['年龄',profile.age],['生日',profile.birthday],['音乐分类',profile.group],['声音或乐器',profile.sound],['代表颜色',profile.color]]){el('dt',label,facts);el('dd',value,facts);}soundButton.disabled=art.silent||!art.audio;soundButton.textContent=soundButton.disabled?'这个角色没有普通声音':'播放角色声音';if(!soundButton.disabled)playSound();}
    title.tabIndex=-1;show(0);return stop;
  }
  function dance(host){
    host.innerHTML='<div class="dance-toolbar"><label>歌曲 <select aria-label="选择歌曲"></select></label></div><p class="dance-status" role="status">上方左边是对手，右边是我方；长音要一直按住</p><div class="dance-stage"><div class="dance-player"><div class="dance-monitor"><div class="dance-face"><span class="dance-eyes"><i></i><i></i></span><span class="dance-mouth"></span></div></div><small>电脑先生</small></div><div class="dance-lanes"><div class="dance-bank dance-opponent-bank"><b>对手</b><canvas aria-label="对手四方向音符"></canvas><div class="dance-targets dance-opponent-targets" aria-label="对手四方向落点"></div></div><i class="dance-divider" aria-hidden="true"></i><div class="dance-bank dance-player-bank"><b>我方</b><canvas aria-label="我方四方向音符"></canvas><div class="dance-targets dance-player-targets" aria-label="我方四方向落点"></div></div></div><div class="dance-rival"><img alt="对战角色"><small></small></div></div>';
    const selects=host.querySelectorAll('select'),songSelect=selects[0],status=host.querySelector('.dance-status'),playerCanvas=host.querySelector('.dance-player-bank canvas'),playerG=playerCanvas.getContext('2d'),opponentCanvas=host.querySelector('.dance-opponent-bank canvas'),opponentG=opponentCanvas.getContext('2d'),player=host.querySelector('.dance-player'),rival=host.querySelector('.dance-rival');
    let library=[...(window.DanceMusic?.tracks||[]).map(t=>({...t,captions:read('lyrics-'+t.id,t.captions||[])})),];
    const computerAppearance='<div class="dance-pose computer-pose" role="img" aria-label="电脑先生：帽子、显示器、支架和桌子"><span class="dance-screen-caption" hidden></span></div><small>电脑先生</small>';
    const poseRows={oren:0,pinki:1,gray:2,wenda:3};
    let liveMix=null,opponentCount=2,playMode='play',customMotion=false,castOverride={},pendingVoice=null,referenceRoles={},referenceEntrances=[],referenceEvent=0,referenceNote=0;
    const stage=host.querySelector('.dance-stage');
    const sun=el('img',undefined,stage);sun.className='dance-sky-sun';sun.alt='太阳公公';sun.src='./assets/sprunki-kiss-local/assets/'+window.DanceCast.mr_sun.idle;
    const friendHud=el('div',undefined,stage);friendHud.className='friend-fnf-hud';friendHud.setAttribute('aria-hidden','true');friendHud.innerHTML='<div class="friend-fnf-top"><span class="friend-fnf-health"><i></i></span><b class="friend-fnf-time">2:30</b></div><strong class="friend-fnf-countdown" hidden>3</strong><div class="friend-fnf-bottom"><b>SCORE: <span data-friend-score>0</span></b><b>MISSES: <span data-friend-misses>0</span></b><b>RATING: <span data-friend-rating>?</span></b></div>';
    const battle=el('div',undefined);battle.className='dance-battle';battle.innerHTML='<span>对手</span><div class="dance-balance" role="progressbar" aria-label="对战胜负进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="55"><i></i><span class="dance-battle-icons"><span class="dance-battle-icon dance-battle-opponent-icon" role="img" aria-label="对手图标"></span><span class="dance-battle-icon dance-battle-player-icon" role="img" aria-label="我方图标"></span></span></div><span>我方 · 得分 <b data-player-score>0</b></span><progress max="1" value="0" aria-label="歌曲进度"></progress>';stage.before(battle);
    const fullscreenButton=btn(host.querySelector('.dance-toolbar'),'电脑全屏',async()=>{if(window.ComputerExperience?.isDamaged()){status.textContent='屏幕正在花屏，修好后才能进入全屏';return;}try{if(document.fullscreenElement===host)await document.exitFullscreen();else await host.requestFullscreen();}catch{status.textContent='浏览器没有允许全屏，请再点一次全屏按钮';}});fullscreenButton.className='dance-fullscreen-toggle';
    const syncSystemFullscreen=()=>{const isFullscreen=document.fullscreenElement===host;host.classList.toggle('dance-system-fullscreen',isFullscreen);fullscreenButton.textContent=isFullscreen?'退出全屏':'电脑全屏';resize();};
    document.addEventListener('fullscreenchange',syncSystemFullscreen);
    const rack=el('div',undefined,host);rack.className='dance-rack';rack.setAttribute('aria-label','拖放角色声部');
    const rackHelp=el('p','拖一个角色到舞台上加入合奏；手机也可点角色加入。再点一次可静音。',host);rackHelp.className='dance-rack-help';
    const loadingStage=el('div',undefined,stage);loadingStage.className='dance-loading-stage';loadingStage.setAttribute('aria-hidden','true');
    for(const [kind,label] of [['character','搬来角色'],['floor','铺开彩色地板'],['sky','装好天空']]){const worker=el('span',undefined,loadingStage);worker.className='dance-loading-worker dance-loading-'+kind;worker.innerHTML='<i></i><b>'+label+'</b>';}
    const failureScene=el('div',undefined,stage);failureScene.className='dance-failure-scene';failureScene.setAttribute('aria-live','polite');failureScene.innerHTML='<span class="dance-failure-icon"><span role="img" aria-label="被拿走的角色图标"></span></span><img class="dance-gray-person" src="./assets/dance-reference/gray-person-cutout.png" alt="小灰人"><strong></strong>';
    const opponentSwap=el('div',undefined,stage);opponentSwap.className='dance-opponent-swap';opponentSwap.setAttribute('aria-hidden','true');opponentSwap.innerHTML='<span class="dance-swap-old" role="img"></span><span class="dance-swap-new" role="img"></span>';
    const roleIconOrder=['oren','raddy','clukr','funbot','vineria','gray','brud','garnold','lime','sky','mr_sun','durple','mr_tree','simon','tunner','computer','wenda','pinki','jevin','black'];
    function setCharacterIcon(node,id){const safe=roleIconOrder.includes(id)?id:'gray';node.classList.add('dance-character-icon');node.dataset.icon=safe;node.style.backgroundImage=`url(./assets/dance-reference/role-icons/${safe}.png)`;node.style.backgroundPosition='center';node.setAttribute('aria-label',(window.DanceCast?.[safe]?.name||safe)+'图标');}
    function useOriginal(figure,id){figure.dataset.character=id;const art=window.DanceCast?.[id];if(id==='black'||(selected?.friendLikeYou&&(id==='mr_tree'||id==='computer'))){figure.replaceChildren();const base=id==='mr_tree'?'mr-tree':id==='computer'?'computer':'black',label=id==='mr_tree'?'树先生':id==='computer'?'电脑先生':'布莱克',actor=el('span',undefined,figure);actor.className='dance-friend-actor '+(id==='computer'?'dance-friend-view':'dance-friend-opponent');actor.dataset.poseBase=base;actor.dataset.pose='idle';actor.dataset.active='0';for(let i=0;i<2;i++){const img=el('img',undefined,actor);img.className='dance-friend-layer'+(i===0?' is-active':'');img.alt=i===0?`Friend Like You ${label}`:'';img.src=`./assets/friend-like-you/${base}-idle.png`;}el('small',label,figure);return;}if(window.DanceReference?.has(id)){figure.replaceChildren();const canvas=el('canvas',undefined,figure);canvas.className='dance-original';canvas.setAttribute('role','img');canvas.setAttribute('aria-label',art?.name||id);window.DanceReference.prepare([id]).then(()=>{if(canvas.isConnected)window.DanceReference.draw(canvas,id,'idle',0);}).catch(()=>{});el('small',art?.name||id,figure);return;}if(!art)return;figure.replaceChildren();const img=el('img',undefined,figure);img.className='dance-original';img.alt=art.name;img.src='./assets/sprunki-kiss-local/assets/'+art.idle;el('small',art.name,figure);}
    function friendPoseMotion(actor,lane){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;actor.getAnimations().forEach(animation=>animation.cancel());const peaks=[{transform:'translate(-32px,-7px) rotate(-7deg) scale(1.02)'},{transform:'translate(0,14px) rotate(0deg) scale(1.035,.96)'},{transform:'translate(0,-30px) rotate(0deg) scale(.99,1.04)'},{transform:'translate(32px,-7px) rotate(7deg) scale(1.02)'}],settles=[{transform:'translate(-10px,-2px) rotate(-2deg)'},{transform:'translate(0,5px) scale(1.015,.985)'},{transform:'translate(0,-9px) scale(.995,1.015)'},{transform:'translate(10px,-2px) rotate(2deg)'}],peak=lane<0?{transform:'translate(0,-6px) rotate(-.5deg) scale(1.01)'}:peaks[lane],settle=lane<0?{transform:'translate(0,1px) rotate(.5deg)'}:settles[lane];actor.animate([{transform:'translate(0,0) rotate(0deg) scale(1)',offset:0},{transform:'translate(0,3px) scale(1.008,.992)',offset:.14},peak,{transform:'translate(0,-2px) rotate(0deg) scale(1.005)',offset:.62},settle,{transform:'translate(0,0) rotate(0deg) scale(1)',offset:1}],{duration:lane<0?820:Math.max(500,poseDuration()+160),easing:'cubic-bezier(.18,.7,.24,1)',fill:'none'});}
    function animateOriginal(figure,t,singing){const id=figure.dataset.character,friendActor=figure.querySelector('.dance-friend-actor');if(friendActor){const lane=Number(figure.dataset.pose??-1),pose=lane<0?'idle':['left','down','up','right'][lane];if(friendActor.dataset.pose!==pose){const layers=friendActor.querySelectorAll('.dance-friend-layer'),active=Number(friendActor.dataset.active||0),next=active?0:1;layers[next].src=`./assets/friend-like-you/${friendActor.dataset.poseBase}-${pose}.png`;layers[next].classList.add('is-active');layers[active].classList.remove('is-active');friendActor.dataset.active=String(next);friendActor.dataset.pose=pose;friendPoseMotion(friendActor,lane);}return;}const canvas=figure.querySelector('canvas.dance-original');if(canvas){const lane=Number(figure.dataset.pose??-1),age=Math.max(0,t-Number(figure.dataset.poseStart||0)),special=figure.dataset.special;let animation=special&&age<.6?special:lane>=0?singAnimationFor(window.DanceReference.animations(id),lane):'idle',elapsed=lane>=0?age:(t%(60/(selected?.bpm||100)));if(selected?.mix&&id==='computer'&&singing&&!customMotion){const phase=Math.max(0,t-2)%9.6;animation=phase<.9?'hello':phase<2.2?'would':phase<3.2?'some':phase<7.7?'us':'fun';elapsed=phase%.6;}window.DanceReference.draw(canvas,id,animation,elapsed);return;}}
    function referenceFrame(t){if(!selected?.reference)return;for(let i=referenceEvent;i<selected.events.length&&selected.events[i].time<t+3;i++){const e=selected.events[i];if(e.character)window.DanceReference.prepare([e.character]).catch(()=>{});}let changed=false;
      while(referenceEvent<selected.events.length&&selected.events[referenceEvent].time<=t){const e=selected.events[referenceEvent++];if('character' in e){const old=referenceRoles[e.side];referenceRoles[e.side]=e.character;if(e.side!=='player'&&e.character&&old!==e.character){if(old)playOpponentIconSwap(old,e.character);const first=selected.notes.find(n=>n.side===e.side&&n.animate&&n.time>=e.time&&n.time<e.time+1.1);referenceEntrances.push({side:e.side,character:e.character,lane:first?.lane??2,until:e.time+.9});}changed=true;}else{const figure=e.side==='player'?player:rival.querySelector('[data-role="'+e.side+'"]');if(figure){figure.dataset.special=e.animation;figure.dataset.poseStart=String(e.time);}}}if(changed){picture();for(const entrance of referenceEntrances.filter(entry=>entry.until>t)){const figure=rival.querySelector('[data-role="'+entrance.side+'"]');if(figure?.dataset.character===entrance.character){setPose(figure,entrance.lane,true);figure.dataset.poseStart=String(t);figure.dataset.poseUntil=String(performance.now()+Math.max(220,(entrance.until-t)*1000));}}}
      referenceEntrances=referenceEntrances.filter(entry=>entry.until>t);const opponentEntering=referenceEntrances.length>0;
      while(referenceNote<selected.notes.length&&selected.notes[referenceNote].time<=t){const n=selected.notes[referenceNote++];if(!n.animate||n.side==='player'&&opponentEntering)continue;const figure=n.side==='player'?player:rival.querySelector('[data-role="'+n.side+'"]');if(!figure)continue;setPose(figure,n.lane,true);figure.dataset.poseStart=String(n.time);delete figure.dataset.special;const hold=performanceHold(n.side,figure.dataset.character,playMode==='watch',n.hold),until=performance.now()+Math.max(0,n.time+hold-t)*1000;if(figure===player)moveUntil=until;else figure.dataset.poseUntil=String(until);}
    }
    function updateBattle(t=0){battle.querySelector('[data-player-score]').textContent=score;battle.querySelector('progress').value=Math.min(1,t/(selected?.duration||40));const balance=battle.querySelector('.dance-balance');balance.style.setProperty('--player-share',playerBalance+'%');balance.setAttribute('aria-valuenow',String(Math.round(playerBalance)));const remaining=Math.max(0,Math.ceil((selected?.duration||0)-t)),minutes=Math.floor(remaining/60),seconds=String(remaining%60).padStart(2,'0'),misses=notes.filter(note=>note.missed).length;friendHud.querySelector('.friend-fnf-time').textContent=`${minutes}:${seconds}`;friendHud.querySelector('[data-friend-score]').textContent=score;friendHud.querySelector('[data-friend-misses]').textContent=misses;friendHud.querySelector('[data-friend-rating]').textContent=score?'GOOD':'?';friendHud.querySelector('.friend-fnf-health').style.setProperty('--friend-health',playerBalance+'%');const countdown=friendHud.querySelector('.friend-fnf-countdown'),countdownText=t<.75?'3':t<1.5?'2':t<2.25?'1':t<3?'开始!':'';countdown.textContent=countdownText;countdown.hidden=!selected?.friendLikeYou||!countdownText;if(playerBalance<=0&&running&&performance.now()-battleStartedAt>=BATTLE_GRACE_MS)playPlayerDefeat();}
    function renderRack(){rack.replaceChildren();rack.hidden=rackHelp.hidden=!selected?.originalMix;if(rack.hidden)return;rackHelp.textContent='拖一个角色到舞台加入原版合奏；再点一次静音。二十位角色均为正常模式。';for(const stem of Object.keys(window.DanceCast).map(id=>({id}))){let suppressClickUntil=0;const b=btn(rack,window.DanceCast?.[stem.id]?.name||stem.id,()=>{if(performance.now()>suppressClickUntil)queueVoice(stem.id);});b.dataset.voice=stem.id;b.draggable=true;b.setAttribute('aria-pressed','false');const icon=el('span',undefined);setCharacterIcon(icon,stem.id);b.prepend(icon);b.ondragstart=e=>{e.dataTransfer.setData('text/plain',stem.id);e.dataTransfer.effectAllowed='copy';};let pointer=null;b.onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY};};b.onpointerup=e=>{if(pointer&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>20){const rect=stage.getBoundingClientRect();if(e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom){e.preventDefault();suppressClickUntil=performance.now()+700;placeVoice(stem.id,e.clientX>rect.left+rect.width*.6?'player':'rival');queueVoice(stem.id,true);}}pointer=null;};b.onpointercancel=()=>{pointer=null;};}}
    function placeVoice(id,side){if(!window.DanceCast[id])return;if(side==='player')castOverride.player=id;else {const old=rival.querySelector(':scope > div')?.dataset.character;const ids=[...(castOverride.rivals||selected.cast||[])].filter(x=>x!==id);castOverride.rivals=[id,...ids];if(old&&old!==id)playOpponentIconSwap(old,id);}picture();}
    async function queueVoice(id,force=false){if(starting&&!running)return;if(!window.DanceCast[id])return;if(!selected?.mix){stopAudio();songSelect.value='mix-sunny';chosen();}if(id==='black'){placeVoice(id,'rival');status.textContent='Black 只展示正常造型，不播放恐怖声音，也不会变换其他角色';return;}const i=selected.mix.findIndex(s=>s.id===id);if(i<0)return;if(!force)placeVoice(id,id==='computer'?'player':'rival');if(!running){pendingVoice=id;begin.click();return;}if(!liveMix)return;const button=rack.querySelector('[data-voice="'+id+'"]'),enabled=force||button?.getAttribute('aria-pressed')!=='true';const at=liveMix.setVoice(i,enabled);if(at===null){status.textContent='歌曲即将结束，重新开始后可加入';return;}button?.setAttribute('aria-pressed',String(enabled));status.textContent=(window.DanceCast[id]?.name||id)+(enabled?'将在下一乐句加入合奏':'将在下一乐句休息');}
    stage.ondragover=e=>{if(selected){e.preventDefault();e.dataTransfer.dropEffect='copy';}};stage.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain'),rect=stage.getBoundingClientRect();placeVoice(id,e.clientX>rect.left+rect.width*.6?'player':'rival');queueVoice(id,true);};
    function addPose(figure,id){if(poseRows[id]===undefined)return;figure.querySelector('img')?.remove();const sprite=el('div',undefined,figure);sprite.className='dance-pose cast-pose';sprite.style.setProperty('--pose-row',poseRows[id]);sprite.setAttribute('role','img');sprite.setAttribute('aria-label',id+'方向动作');figure.prepend(sprite);}
    const poseAnimations=new Map();
    function poseDuration(){return Math.max(280,Math.min(520,60000/(selected?.bpm||100)*.75));}
    function setPose(figure,lane,replay=false){const shownLane=lane<0?lane:orientedLane(figure.dataset.side,lane);if(!replay&&figure.dataset.pose===String(shownLane))return;const sprite=figure.querySelector('.dance-friend-actor,.dance-pose,img,canvas.dance-original');figure.dataset.poseStart=String(time());poseAnimations.get(figure)?.cancel();poseAnimations.delete(figure);figure.dataset.pose=String(shownLane);figure.dataset.view=shownLane===1?'front':shownLane===2?'back':'side';figure.style.setProperty('--pose-x',((shownLane<0?1:shownLane)*100/3)+'%');if(shownLane<0||!sprite||(!customMotion&&sprite.classList.contains('dance-original'))||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
      const peak=['translate(-10px,-2px) rotate(-9deg) scale(1.04,.98)','translate(0,9px) rotate(2deg) scale(1.12,.84)','translate(0,-14px) rotate(-2deg) scale(.91,1.12)','translate(10px,-2px) rotate(9deg) scale(1.04,.98)'][shownLane];
      const settle=['translate(-4px,0) rotate(-3deg)','translate(0,3px) scale(1.03,.97)','translate(0,-4px) scale(.99,1.03)','translate(4px,0) rotate(3deg)'][shownLane];
      const animation=sprite.animate([{transform:'translate(0,0) scale(1)',offset:0},{transform:'translate(0,3px) scale(1.025,.965)',offset:.14},{transform:peak,offset:.38},{transform:settle,offset:.73},{transform:'translate(0,0) scale(1)',offset:1}],{duration:poseDuration(),easing:'cubic-bezier(.22,.65,.35,1)',fill:'forwards'});poseAnimations.set(figure,animation);
    }
    function updateScreen(t){const screen=player.querySelector('.dance-screen-caption');if(!screen)return;const words=player.classList.contains('singing')?window.DanceMusic.captionForTrack(selected,t):'';screen.hidden=!words;if(screen.textContent!==words)screen.textContent=words;}
    const picture=()=>{const lead=castOverride.player||referenceRoles.player||leadCharacter(selected);player.replaceChildren();player.classList.remove('singing');player.dataset.side='player';useOriginal(player,lead);setPose(player,-1);player.dataset.character=lead||'partner';rival.replaceChildren();const ids=selected?.reference?[referenceRoles.dad,referenceRoles.gf]:(castOverride.rivals||selected?.cast||[]).filter(id=>id!==lead).slice(0,opponentCount);sun.hidden=!!selected?.friendLikeYou||!stageSunVisible([lead,...ids].filter(Boolean));ids.forEach((id,i)=>{if(!id)return;const figure=el('div',undefined,rival);figure.dataset.role=i===0?'dad':'gf';figure.dataset.side='opponent';useOriginal(figure,id);setPose(figure,-1);});setCharacterIcon(battle.querySelector('.dance-battle-player-icon'),lead);setCharacterIcon(battle.querySelector('.dance-battle-opponent-icon'),ids.find(Boolean)||'black');};
    let demoTimer=0;
    let ctx,raf=0,active=true,running=false,notes=[],opponentNotes=[],startTime=0,score=0,combo=0,playerBalance=55,battleStartedAt=0,failureActive=false,failureReturnTimer=0,failureEndTimer=0,opponentSwapTimer=0,rivalScore=0,nextSound=0,moveUntil=0,rivalBeat=-1,friendCrowdBeat=-1,selected=library[0],media=null,mediaStems=[],mediaURL=null,db=null,starting=false,importing=false,video=null,playSession=0;const arrows=['←','↓','↑','→'],heldLanes=new Set(),activeHolds=new Map();
    function clearDanceFailure(){clearTimeout(failureReturnTimer);clearTimeout(failureEndTimer);failureActive=false;failureScene.classList.remove('is-active','is-player-defeat','is-returning');failureScene.querySelector('strong').textContent='';player.classList.remove('dance-role-lost');rack.querySelectorAll('.role-taken').forEach(b=>b.classList.remove('role-taken'));}
    function playOpponentIconSwap(oldId,newId){if(!window.DanceCast?.[oldId]||!window.DanceCast?.[newId])return;clearTimeout(opponentSwapTimer);setCharacterIcon(opponentSwap.querySelector('.dance-swap-old'),oldId);setCharacterIcon(opponentSwap.querySelector('.dance-swap-new'),newId);opponentSwap.classList.remove('is-swapping');void opponentSwap.offsetWidth;opponentSwap.classList.add('is-swapping');opponentSwapTimer=setTimeout(()=>opponentSwap.classList.remove('is-swapping'),720);}
    function playPlayerDefeat(){if(failureActive||playMode==='watch')return;failureActive=true;running=false;const id=player.dataset.character||'simon',name=window.DanceCast?.[id]?.name||'西蒙',button=rack.querySelector('[data-voice="'+id+'"]'),icon=failureScene.querySelector('.dance-failure-icon .dance-character-icon')||failureScene.querySelector('.dance-failure-icon span');setCharacterIcon(icon,id);player.classList.add('dance-role-lost');button?.classList.add('role-taken');failureScene.querySelector('strong').textContent='我方输了';failureScene.classList.add('is-active','is-player-defeat');liveMix?.stop();media?.pause();mediaStems.forEach(stem=>stem.pause());status.textContent=`我方输了 · ${name}的图标正在回来`;failureReturnTimer=setTimeout(()=>{failureScene.classList.add('is-returning');player.classList.remove('dance-role-lost');button?.classList.remove('role-taken');status.textContent=`${name}的图标回来了 · 点重新开始再挑战`;},3200);failureEndTimer=setTimeout(()=>{failureScene.classList.remove('is-active','is-player-defeat','is-returning');failureScene.querySelector('strong').textContent='';failureActive=false;},5000);}
    function changePlayerBalance(amount){if(playMode==='watch'||failureActive)return;playerBalance=Math.max(0,Math.min(100,playerBalance+amount));updateBattle(time());}
    const friendFloor=el('div',undefined,stage);friendFloor.className='friend-finale-floor';
    const friendCrowd=el('div',undefined,stage);friendCrowd.className='friend-chorus-crowd';for(const id of ['durple','wenda','vineria','jevin','oren','raddy','pinki','simon','tunner','gray']){const figure=el('div',undefined,friendCrowd);figure.dataset.side='opponent';useOriginal(figure,id);setPose(figure,-1);}
    const danceArrowColors=[[198,107,234],[67,220,237],[120,230,90],[255,98,110]];
    function colorizeDanceArrow(image,lane){const colored=document.createElement('canvas');image.onload=()=>{colored.width=image.naturalWidth;colored.height=image.naturalHeight;const g=colored.getContext('2d',{willReadFrequently:true});g.drawImage(image,0,0);const pixels=g.getImageData(0,0,colored.width,colored.height),fill=danceArrowColors[lane],light=[240,252,255],outline=[29,38,59];for(let i=0;i<pixels.data.length;i+=4){const r=pixels.data[i]/255,green=pixels.data[i+1]/255,b=pixels.data[i+2]/255;pixels.data[i]=Math.min(255,fill[0]*r+light[0]*green+outline[0]*b);pixels.data[i+1]=Math.min(255,fill[1]*r+light[1]*green+outline[1]*b);pixels.data[i+2]=Math.min(255,fill[2]*r+light[2]*green+outline[2]*b);}g.putImageData(pixels,0,0);};return colored;}
    const danceArrowImages=['left','down','up','right'].map((direction,lane)=>{const image=new Image(),colored=colorizeDanceArrow(image,lane);image.src='./assets/dance-reference/arrows/note-'+direction+'.png';return colored;});
    const libraryBox=el('details',undefined);libraryBox.className='dance-library';host.prepend(libraryBox);el('summary','更多歌曲 / 本机音频',libraryBox);
    const cards=el('div',undefined);cards.className='dance-song-cards';cards.setAttribute('aria-label','点歌即玩');host.prepend(cards);
    const videoBox=el('div',undefined,host.querySelector('.dance-stage'));videoBox.className='dance-video';videoBox.hidden=true;
    const search=el('input',undefined,libraryBox);search.type='search';search.placeholder='搜索歌名';search.setAttribute('aria-label','搜索歌名');
    const filterLabel=el('label','只看歌名带 SPRUNKI 的歌曲',libraryBox),filter=el('input',undefined,filterLabel);filter.type='checkbox';
    const importLabel=el('label','批量导入歌曲',libraryBox),files=el('input',undefined,importLabel);files.type='file';files.accept='.mp3,.wav,.ogg,.m4a,.aac,.flac,.webm';files.multiple=true;files.disabled=true;
    const libraryStatus=el('p','正在打开本机歌曲库…',libraryBox);libraryStatus.setAttribute('role','status');
    const tempoLabel=el('label','节拍速度 BPM',libraryBox),tempo=el('input',undefined,tempoLabel);tempo.type='number';tempo.min=40;tempo.max=240;tempo.value=120;tempo.setAttribute('aria-label','歌曲节拍速度');
    el('small','导入完整音频后可选歌对战，保存在本机。每首最多 25 MB、15 分钟。导入曲目的箭头按所设节拍生成，可调整 BPM；不是原曲官方谱面。',libraryBox);
    const lyricLabel=el('label','为当前歌曲添加定时歌词（LRC）',libraryBox),lyricFile=el('input',undefined,lyricLabel);lyricFile.type='file';lyricFile.accept='.lrc';lyricFile.onchange=async()=>{const file=lyricFile.files[0],track=selected;if(!file||!track)return;if(file.size>200000){libraryStatus.textContent='歌词文件太大';return;}const cues=window.DanceMusic.parseLyrics(await file.text());if(!cues.length){libraryStatus.textContent='没有找到带时间的歌词';return;}track.captions=cues;const stored=save('lyrics-'+track.id,cues);libraryStatus.textContent=stored?'歌词已保存，会在电脑先生唱歌时显示在屏幕上':'歌词已载入，本机保存失败';lyricFile.value='';};
    const sources=el('details',undefined,libraryBox);sources.className='dance-song-sources';el('summary','找歌曲 · 原曲与作者页面',sources);el('p','这些是歌曲来源链接，需要联网打开。拿到可播放的音频文件后，可用上面的导入按钮加入对战。',sources);
    for(const source of songSources){const link=el('a',source.name+' — '+source.artist,sources);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';}
    const remove=btn(libraryBox,'移除所选导入歌曲',async()=>{if(!selected?.imported||running||starting)return;try{await transaction(['tracks','audio'],'readwrite',tx=>{tx.objectStore('tracks').delete(selected.id);tx.objectStore('audio').delete(selected.id);});library=library.filter(s=>s.id!==selected.id);renderSongs();libraryStatus.textContent='已移除歌曲';}catch{libraryStatus.textContent='移除失败，请重试';}});
    function transaction(stores,mode,action){return new Promise((resolve,reject)=>{if(!db){reject(Error('歌曲库不可用'));return;}const tx=db.transaction(stores,mode);let req;try{req=action(tx);}catch(e){reject(e);return;}tx.oncomplete=()=>resolve(req?.result);tx.onerror=tx.onabort=()=>reject(tx.error||Error('存储失败'));});}
    const request=indexedDB.open('computer-dance-library',1);request.onupgradeneeded=()=>{request.result.createObjectStore('tracks',{keyPath:'id'});request.result.createObjectStore('audio');};request.onsuccess=async()=>{db=request.result;if(!active){db.close();return;}try{const tracks=await transaction(['tracks'],'readonly',tx=>tx.objectStore('tracks').getAll());if(!active)return;library.push(...tracks.map(t=>({...t,captions:read('lyrics-'+t.id,[])})));renderSongs();files.disabled=false;libraryStatus.textContent=tracks.length?`已载入 ${tracks.length} 首导入歌曲`:'两首原曲及正常模式音色随游戏提供；没有视频广告或恐怖曲目。';}catch{libraryStatus.textContent='歌曲库读取失败；练习曲仍可玩。';}};request.onerror=()=>libraryStatus.textContent='本机存储不可用，无法保存导入歌曲。';
    function chosen(){selected=library.find(s=>s.id===songSelect.value);castOverride={};referenceRoles={...(selected?.initial||{})};referenceEntrances=[];referenceEvent=referenceNote=0;host.classList.toggle('friend-safe-stage',!!selected?.friendLikeYou);host.classList.remove('friend-single-bank');renderRack();opponents.disabled=!!selected?.reference;host.style.setProperty('--dance-beat',(60/(selected?.bpm||100))+'s');if(!running&&!starting)picture();tempo.value=selected?.bpm||120;tempo.disabled=!selected?.imported;remove.disabled=!selected?.imported;begin.disabled=!selected||starting;if(running||starting)lock(true);}
    function renderSongs(){const old=songSelect.value;cards.replaceChildren();for(const track of library.filter(s=>s.reference||s.video||s.mix)){const card=btn(cards,track.name+' · '+track.artist,()=>{stopAudio();search.value='';filter.checked=false;renderSongs();songSelect.value=track.id;chosen();begin.click();});card.dataset.song=track.id;} songSelect.replaceChildren();for(const s of library.filter(s=>matchesSong(s,search.value,filter.checked))){const kind=s.friendLikeYou?'本地可玩关卡':s.reference?'原曲 · 原谱面':s.video?'在线原曲':s.mix?(s.originalMix?'原版合奏':'自由合奏'):s.imported?'原文件':'自制练习',o=el('option',`${s.name} · ${kind} · ${Math.round(s.bpm*100)/100} BPM`,songSelect);o.value=s.id;}if([...songSelect.options].some(o=>o.value===old))songSelect.value=old;chosen();if(!selected){status.textContent='没有匹配歌曲。可清除筛选，或导入带 SPRUNKI 名字的音频文件。';}else if(!running&&!video&&!starting)status.textContent=`已选择：${selected.name} · 点上方歌名即可开始`;}
    search.oninput=filter.onchange=renderSongs;songSelect.onchange=()=>{stopAudio();chosen();begin.click();};
    tempo.onchange=async()=>{if(!selected?.imported)return;selected.bpm=Math.max(40,Math.min(240,Number(tempo.value)||120));tempo.value=selected.bpm;try{await transaction(['tracks'],'readwrite',tx=>tx.objectStore('tracks').put(selected));renderSongs();}catch{libraryStatus.textContent='节拍已更改，但保存失败。';}};
    function durationOf(file){return new Promise((resolve,reject)=>{const a=new Audio(),url=URL.createObjectURL(file);const timer=setTimeout(()=>finish(Error('读取超时')),10000);function finish(error){clearTimeout(timer);const duration=a.duration;a.removeAttribute('src');a.load();URL.revokeObjectURL(url);error?reject(error):resolve(duration);}a.onloadedmetadata=()=>finish();a.onerror=()=>finish(Error('格式不能播放'));a.preload='metadata';a.src=url;});}
    files.onchange=async()=>{if(running||starting)return;importing=true;files.disabled=true;const batch=[...files.files];let added=0;const failures=[];for(const file of batch){if(!active)break;if(!audioFileAllowed(file)){failures.push(file.name+'：格式不支持或超过 25 MB');continue;}const id=`file-${file.name}-${file.size}-${file.lastModified}`;if(library.some(s=>s.id===id))continue;try{const duration=await durationOf(file);if(!active)break;if(!Number.isFinite(duration)||duration<4||duration>900)throw Error('时长需为 4 秒至 15 分钟');const track={id,name:file.name.replace(/\.[^.]+$/,''),duration,bpm:120,imported:true};await transaction(['tracks','audio'],'readwrite',tx=>{tx.objectStore('tracks').put(track);tx.objectStore('audio').put(file,id);});library.push(track);added++;libraryStatus.textContent=`已导入 ${added} 首…`;}catch(e){failures.push(file.name+'：'+e.message);}}importing=false;if(active){files.value='';files.disabled=running||starting;renderSongs();libraryStatus.textContent=`已添加 ${added} 首。${failures.join('；')}`;}};
    function lock(value){files.disabled=value||importing||!db;songSelect.disabled=starting;search.disabled=filter.disabled=value;tempo.disabled=value||!selected?.imported;remove.disabled=value||!selected?.imported;}
    function stopAudio(){liveMix?.stop();liveMix=null;heldLanes.clear();activeHolds.clear();clearDanceFailure();clearTimeout(opponentSwapTimer);opponentSwap.classList.remove('is-swapping');host.classList.remove('friend-single-bank','friend-night-phase','friend-chorus-phase','friend-opening-phase');friendCrowdBeat=-1;rack.querySelectorAll('[data-voice]').forEach(b=>{b.dataset.singing='false';b.setAttribute('aria-pressed','false');});clearInterval(demoTimer);demoTimer=0;poseAnimations.forEach(a=>a.cancel());poseAnimations.clear();playSession++;running=false;resume.hidden=true;if(video){video.destroy();video=null;}videoBox.replaceChildren();videoBox.hidden=true;for(const stem of mediaStems){stem.onended=stem.onerror=null;stem.pause();stem.removeAttribute('src');stem.load();}if(mediaStems.length)media=null;mediaStems=[];if(media){media.onended=media.onerror=null;media.pause();media.removeAttribute('src');media.load();media=null;}if(mediaURL){URL.revokeObjectURL(mediaURL);mediaURL=null;}if(ctx){ctx.close();ctx=null;}rival.style.transform='';player.classList.remove('singing');setPose(player,-1);updateScreen(0);rival.querySelectorAll(':scope > div').forEach(f=>{f.classList.remove('singing');f.style.transform='';setPose(f,-1);f.dataset.poseUntil='0';});lock(false);}
    function finish(){updateBattle(selected?.duration||0);stopAudio();status.textContent=`歌曲结束 · 得分 ${score}`;}
    const begin=btn(host.querySelector('.dance-toolbar'),'开始演唱',async()=>{if(!selected||starting)return;const loadingStarted=performance.now();starting=true;host.classList.add('game-is-loading');begin.disabled=true;stopAudio();const session=playSession;retry.hidden=true;resume.hidden=true;lock(true);cards.querySelectorAll('button').forEach(b=>b.disabled=true);try{status.textContent='正在准备：'+selected.name;const split=battleChart(selected),fullLaneStart=n=>!selected.reference||n.time>=NOTE_TRAVEL_SECONDS;notes=playMode==='watch'?[]:split.player.filter(fullLaneStart);opponentNotes=playMode==='watch'?[]:split.opponent.filter(fullLaneStart);score=combo=rivalScore=nextSound=0;playerBalance=55;battleStartedAt=0;rivalBeat=-1;referenceRoles={...(selected.initial||{})};referenceEntrances=[];referenceEvent=referenceNote=0;picture();updateBattle();await window.DanceReference.prepare([player.dataset.character,...Array.from(rival.children,f=>f.dataset.character)]);if(!active||session!==playSession)return;if(selected.video){videoBox.hidden=false;const credit=el('p',selected.name+' — '+selected.artist+' · 在线原曲 · 练习谱面 / 舞台搭档',videoBox);const slot=el('div',undefined,videoBox);status.textContent='正在连接原曲…';const openedVideo=await window.DanceMusic.open(slot,selected,{
      loading:message=>{if(active&&session===playSession){running=false;status.textContent=message;}},
      state:(state,p)=>{if(!active||session!==playSession)return;resume.hidden=state===1;if(state===1){const duration=p.getDuration();if(duration>3&&playMode!=='watch'&&notes.length!==chart({...selected,duration}).length)notes=notesForMode({...selected,duration},playMode);running=true;if(!battleStartedAt)battleStartedAt=performance.now();status.textContent=playMode==='watch'?'观战模式：没有箭头，听歌看完整表演':'正在播放：'+selected.name+' · 接住白线上的箭头';}else if(state===0)finish();else{running=false;status.textContent=state===3?'音乐缓冲中…':'点击原曲播放器的播放按钮继续';}},
      blocked:()=>{if(active&&session===playSession){running=false;resume.hidden=false;status.textContent='浏览器暂停了自动播放，请点“播放声音”';}},
      error:message=>{if(session===playSession){stopAudio();retry.hidden=false;status.textContent=message;}}
    });if(!active||session!==playSession){openedVideo?.destroy();return;}video=openedVideo;begin.textContent='重新开始';return;
    }else if(selected.mix){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const schedule=await window.DanceMusic.prepareLiveMix(ctx,selected);if(!active||session!==playSession)return;startTime=ctx.currentTime+.1;liveMix=schedule(startTime);videoBox.hidden=true;}else if(selected.audioStems){mediaStems=selected.audioStems.map(source=>new Audio(source));media=mediaStems[0];media.onended=finish;for(const stem of mediaStems)stem.onerror=()=>{stopAudio();retry.hidden=false;status.textContent='本机歌曲读取失败，请重试';};await Promise.all(mediaStems.map(stem=>stem.play()));if(!active||session!==playSession)return;videoBox.hidden=true;}else if(selected.audioFile){media=new Audio(selected.audioFile);media.onended=finish;media.onerror=()=>{stopAudio();retry.hidden=false;status.textContent='本机歌曲读取失败，请重试';};await media.play();if(!active||session!==playSession)return;videoBox.hidden=true;}else if(selected.mix){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const schedule=await window.DanceMusic.prepareMix(ctx,selected);if(!active||session!==playSession)return;startTime=ctx.currentTime;schedule(startTime);videoBox.hidden=true;}else if(selected.imported){const blob=await transaction(['audio'],'readonly',tx=>tx.objectStore('audio').get(selected.id));if(!active)return;if(!blob)throw Error('音频文件缺失');mediaURL=URL.createObjectURL(blob);media=new Audio(mediaURL);media.onended=finish;media.onerror=()=>{stopAudio();status.textContent='这首歌无法播放，请重新导入可播放的音频';};await media.play();}else{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();startTime=ctx.currentTime;}if(!active){stopAudio();return;}running=true;battleStartedAt=performance.now();if(pendingVoice){const id=pendingVoice;pendingVoice=null;queueVoice(id,true);}begin.textContent='重新开始';status.textContent=playMode==='watch'?`观战模式：${selected.name} · 没有箭头，听歌看完整表演`:selected.reference?`正在播放：${selected.name} · 右边我方演唱时接箭头`:`正在播放：${selected.name} · 拖入角色组成原版合奏`;}catch(e){if(active&&session===playSession){stopAudio();retry.hidden=false;status.textContent='歌曲未能播放：'+e.message;}}finally{const loadingRemain=900-(performance.now()-loadingStarted);if(loadingRemain>0)await new Promise(resolve=>setTimeout(resolve,loadingRemain));host.classList.remove('game-is-loading');starting=false;begin.disabled=!selected;songSelect.disabled=false;cards.querySelectorAll('button').forEach(b=>b.disabled=false);}});
    const retry=btn(host.querySelector('.dance-toolbar'),'重试原曲',()=>begin.click());retry.hidden=true;const resume=btn(host.querySelector('.dance-toolbar'),'播放声音',()=>video?.playVideo());resume.hidden=true;
    btn(host.querySelector('.dance-toolbar'),'停止 / 换歌',()=>{if(starting)return;stopAudio();status.textContent='已停止，可以重新选择歌曲';});
    const modeLabel=el('label','模式 ',host.querySelector('.dance-toolbar')),mode=el('select',undefined,modeLabel);mode.setAttribute('aria-label','游玩模式');for(const [value,name] of [['play','跟唱接拍'],['watch','观战听歌']]){const o=el('option',name,mode);o.value=value;}mode.onchange=()=>{playMode=mode.value;host.classList.toggle('dance-watch-mode',playMode==='watch');if(running||starting)stopAudio();status.textContent=playMode==='watch'?'观战模式没有箭头；选歌后听歌看角色完整表演':'跟唱接拍模式：右边我方演唱时接箭头';};
    const opponentsLabel=el('label','对手 ',host.querySelector('.dance-toolbar')),opponents=el('select',undefined,opponentsLabel);opponents.setAttribute('aria-label','对手人数');for(const n of [1,2]){const o=el('option',n+' 位',opponents);o.value=n;}opponents.value=2;opponents.onchange=()=>{opponentCount=Number(opponents.value);if(!selected?.reference)picture();};
    const motionLabel=el('label','动作 ',host.querySelector('.dance-toolbar')),motion=el('select',undefined,motionLabel);motion.setAttribute('aria-label','角色动作模式');for(const [value,name] of [['original','原版角色动作'],['custom','自创方向动作']]){const o=el('option',name,motion);o.value=value;}motion.onchange=()=>{customMotion=motion.value==='custom';host.classList.toggle('dance-custom-motion',customMotion);};
    btn(host.querySelector('.dance-toolbar'),'四方向动作演示',()=>{if(starting)return;stopAudio();customMotion=true;motion.value='custom';host.classList.add('dance-custom-motion');let lane=0;const tick=()=>{if(!active)return;setPose(player,lane,true);moveUntil=performance.now()+poseDuration();rival.querySelectorAll(':scope > div').forEach(f=>{setPose(f,lane,true);f.dataset.poseUntil=String(moveUntil);});status.textContent=['向左：侧头探出，再回弹','向下：压低身体，再弹起','向上：抬头伸展，再落回','向右：侧向右边，再回弹'][lane]+' · 点停止结束演示';lane=(lane+1)%4;};tick();demoTimer=setInterval(tick,Math.max(720,poseDuration()+220));});renderSongs();
    function time(){return video?video.getCurrentTime():media?media.currentTime:ctx?Math.max(0,ctx.currentTime-(ctx.outputLatency||0)-startTime):0;}
    function drawArrow(context,lane,x,y,size){const image=danceArrowImages[lane],sourceWidth=image?.naturalWidth||image?.width,sourceHeight=image?.naturalHeight||image?.height;if(!sourceWidth||!sourceHeight)return;const ratio=sourceWidth/sourceHeight,width=size*ratio;context.drawImage(image,x-width/2,y-size/2,width,size);}
    function drawHoldTail(context,lane,x,headY,endY,size,hold){if(!(hold>.02)||Math.abs(endY-headY)<2)return;const colors=['#c66bea','#43dced','#78e65a','#ff626e'],width=Math.max(12,size*.3),top=Math.min(headY,endY),height=Math.abs(headY-endY);context.save();context.globalAlpha=.94;context.lineJoin='round';context.lineCap='round';context.strokeStyle='#17252c';context.lineWidth=Math.max(5,size*.1);context.fillStyle=colors[lane];context.beginPath();context.roundRect(x-width/2,top,width,height,Math.min(width*.45,8));context.fill();context.stroke();context.globalAlpha=.42;context.fillStyle='#ffffff';context.fillRect(x-width*.12,top+3,width*.24,Math.max(0,height-6));context.restore();}
    function releaseLane(lane){heldLanes.delete(lane);const activeHold=activeHolds.get(lane);if(activeHold&&time()<activeHold.time+activeHold.hold-.08){activeHold.done=true;activeHold.missed=true;activeHolds.delete(lane);combo=0;changePlayerBalance(-12);status.textContent=`长音松开太早 · 得分 ${score} · 连击 0`;}}
    function hit(lane){if(!running)return;heldLanes.add(lane);const t=time(),n=notes.find(n=>!n.done&&!n.headHit&&n.lane===lane&&Math.abs(n.time-t)<=.28),points=n?grade(n.time-t):0;if(n){score+=points;combo++;changePlayerBalance(points===100?6:4);if(n.hold>.08){n.headHit=true;activeHolds.set(lane,n);status.textContent=`长音开始，继续按住 · 得分 ${score} · 连击 ${combo}`;}else n.done=true;}else{combo=0;changePlayerBalance(-4);}if(!selected.reference){setPose(player,lane,true);moveUntil=performance.now()+poseDuration();}const target=host.querySelectorAll('.dance-player-targets button')[lane];target.dataset.feedback=points?'hit':'miss';target.dataset.until=String(performance.now()+poseDuration());if(!n?.hold)status.textContent=`${points===100?'完美':points?'接住了':'没接到'} · 得分 ${score} · 连击 ${combo}`;}
    arrows.forEach((a,i)=>{const direction=['left','down','up','right'][i],playerTarget=btn(host.querySelector('.dance-player-targets'),a,()=>{}),opponentTarget=el('span',undefined,host.querySelector('.dance-opponent-targets'));playerTarget.setAttribute('aria-label',['左','下','上','右'][i]+'方向落点');playerTarget.innerHTML='<img src="./assets/dance-reference/arrows/receptor-'+direction+'.png" alt="">';opponentTarget.innerHTML='<img src="./assets/dance-reference/arrows/receptor-'+direction+'.png" alt="">';playerTarget.onpointerdown=e=>{e.preventDefault();hit(i);};playerTarget.onpointerup=playerTarget.onpointercancel=()=>releaseLane(i);});const key=e=>{const i=['ArrowLeft','ArrowDown','ArrowUp','ArrowRight'].indexOf(e.key);if(i>=0&&!e.repeat&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();hit(i);}};const keyUp=e=>{const i=['ArrowLeft','ArrowDown','ArrowUp','ArrowRight'].indexOf(e.key);if(i>=0)releaseLane(i);};document.addEventListener('keydown',key);document.addEventListener('keyup',keyUp);
    function frame(){if(!active)return;raf=requestAnimationFrame(frame);const prepare=(canvas,context,side)=>{const w=Math.max(120,Math.floor(canvas.clientWidth)),h=Math.max(110,Math.floor(canvas.clientHeight));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}context.clearRect(0,0,w,h);const line=noteTravelBounds(side,h,0,!!selected?.friendLikeYou).target;return {w,h,line,side};};const playerBox=prepare(playerCanvas,playerG,'player'),opponentBox=prepare(opponentCanvas,opponentG,'opponent');const colors=['#c66bea','#43dced','#78e65a','#ff626e'];const now=performance.now();if(now>moveUntil)setPose(player,-1);host.querySelectorAll('.dance-targets [data-feedback]').forEach(b=>{if(now>Number(b.dataset.until))delete b.dataset.feedback;});rival.querySelectorAll(':scope > div').forEach(f=>{if(now>Number(f.dataset.poseUntil||0))setPose(f,-1);});if(!running){animateOriginal(player,0,false);rival.querySelectorAll(':scope > div').forEach(f=>animateOriginal(f,0,false));return;}const t=time();referenceFrame(t);const nightStart=selected.phases?.nightStart??55,finaleStart=selected.phases?.finaleStart??115,friendOpening=!!selected.friendLikeYou&&t<2.4,friendNight=!!selected.friendLikeYou&&t>=nightStart&&t<finaleStart,friendChorus=!!selected.friendLikeYou&&t>=finaleStart;host.classList.toggle('friend-opening-phase',friendOpening);host.classList.toggle('friend-single-bank',friendNight);host.classList.toggle('friend-night-phase',friendNight);host.classList.toggle('friend-chorus-phase',friendChorus);const friendBeat=Math.floor(Math.max(0,t-finaleStart)/(60/selected.bpm));if(friendChorus&&friendBeat!==friendCrowdBeat){friendCrowdBeat=friendBeat;friendCrowd.querySelectorAll(':scope > div').forEach((f,i)=>setPose(f,(friendBeat+i)%4,true));}friendCrowd.querySelectorAll(':scope > div').forEach(f=>animateOriginal(f,t,friendChorus));
      // Schedule music ahead against the audio clock, not animation-frame timing.
      while(!selected.reference&&!selected.video&&!selected.imported&&!selected.mix&&nextSound<notes.length&&notes[nextSound].time<t+.18){const i=nextSound++,n=notes[i],when=startTime+n.time;if(when>=ctx.currentTime){sound(ctx,220*2**(selected.scale[i%8]/12),when,.24,'triangle');sound(ctx,i%4===0?65:110,when,.1,'sine',.12);if(i%2===0)sound(ctx,880,when,.035,'square',.018);}}
      const voices=selected.mix?(liveMix?.voicesAt(t)||[]):[];
      if(selected.mix){const singing=f=>voices.some(i=>selected.mix[i].id===f.dataset.character);rival.querySelectorAll(':scope > div').forEach(f=>f.classList.toggle('singing',singing(f)));player.classList.toggle('singing',singing(player));rack.querySelectorAll('[data-voice]').forEach(b=>{b.dataset.singing=String(voices.some(i=>selected.mix[i].id===b.dataset.voice));});}
      animateOriginal(player,t,player.classList.contains('singing'));rival.querySelectorAll(':scope > div').forEach(f=>animateOriginal(f,t,f.classList.contains('singing')));
      if(selected.vocalWindows)player.classList.toggle('singing',selected.vocalWindows.some(([from,to])=>t>=from&&t<to));
      const beat=Math.floor(Math.max(0,t-2)/(60/selected.bpm));if(!selected.reference&&beat!==rivalBeat){rivalBeat=beat;if(player.classList.contains('singing')){setPose(player,beat%4,true);moveUntil=now+poseDuration();}else setPose(player,-1);rival.querySelectorAll(':scope > div').forEach((f,i)=>{if(f.classList.contains('singing')||!selected.mix){setPose(f,(beat+i)%4,true);f.dataset.poseUntil=String(now+poseDuration());}else setPose(f,-1);});}updateScreen(t);updateBattle(t);
      activeHolds.forEach((n,lane)=>{if(t>=n.time+n.hold){n.done=true;activeHolds.delete(lane);score+=100;changePlayerBalance(6);status.textContent=`长音完成 · 得分 ${score} · 连击 ${combo}`;}else if(!heldLanes.has(lane)){n.done=true;n.missed=true;activeHolds.delete(lane);combo=0;changePlayerBalance(-12);}});
      const drawNotes=(list,box,context,automatic=false)=>list.forEach(n=>{if(automatic&&!n.done&&t>=n.time){n.done=true;const target=host.querySelectorAll('.dance-opponent-targets span')[n.lane];if(target){target.dataset.feedback='hit';target.dataset.until=String(now+poseDuration());}}else if(!automatic&&!n.done&&!n.headHit&&t>n.time+.28){n.done=true;n.missed=true;combo=0;changePlayerBalance(-4);}if((!n.done||n.headHit)&&n.time-t<=NOTE_TRAVEL_SECONDS){const size=Math.min(52,box.w/4*.72),path=noteTravelBounds(box.side,box.h,size,!!selected?.friendLikeYou),y=n.headHit?path.target:noteTravelY(n.time,t,path.start,path.target),x=(n.lane+.5)*box.w/4,endY=noteTravelY(n.time+n.hold,t,path.start,path.target);if(y>-size&&y<=box.h+size){drawHoldTail(context,n.lane,x,y,endY,size,n.hold);drawArrow(context,n.lane,x,y,size);}}});
      drawNotes(notes,playerBox,playerG);drawNotes(opponentNotes,opponentBox,opponentG,true);
      if(!selected.video&&!selected.imported&&!media&&t>(selected.mix?selected.duration:(notes.at(-1)?.time||selected.duration||0)+1))finish();
    }frame();return()=>{active=false;stopAudio();cancelAnimationFrame(raf);document.removeEventListener('keydown',key);document.removeEventListener('keyup',keyUp);document.removeEventListener('fullscreenchange',syncSystemFullscreen);if(document.fullscreenElement===host)document.exitFullscreen().catch(()=>{});db?.close();};
  }
  function blocks(host) { return window.VoxelWorld.mount(host); }
  window.ComputerApps={catalog,mount};
})();
