/* Local game resources only; external video and API requests are never cached. */
const CACHE='mr-computer-20260923-games1',PREFIX='mr-computer-',CORE=["./","./index.html","./styles.css?v=20260923-games1","./game-runtime.js?v=20260923-games1","./computer-apps.css?v=20260923-games1","./voxel-rules.js?v=20260923-games1","./voxel-terrain.js?v=20260923-games1","./voxel-workstations.js?v=20260923-games1","./voxel-audio.js?v=20260923-games1","./voxel-survival.js?v=20260923-games1","./voxel-shell.js?v=20260923-games1","./voxel-world.js?v=20260923-games1","./dance-music.js?v=20260923-games1","./computer-apps.js?v=20260923-games1","./computer-knowledge.js?v=20260923-games1","./app.js?v=20260923-games1","./computer-voice.js?v=20260923-games1","./computer-experience.js?v=20260923-games1","./rhythm-world/vendor/three.module.min.js"];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);await cache.addAll(CORE);})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith(PREFIX)&&key!==CACHE)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url),root=new URL(self.registration.scope);if(request.method!=='GET'||url.origin!==root.origin||!url.pathname.startsWith(root.pathname)||url.pathname.includes('/api/')||url.pathname.includes('/__'))return;
const local=/\.(js|css|json|png|jpg|jpeg|svg|webp|wav|mp3|ogg|woff2|html)$/.test(url.pathname)||request.mode==='navigate';if(!local)return;
event.respondWith((async()=>{const cache=await caches.open(CACHE);const save=async response=>{if(response.ok&&response.type!=='opaque'){try{await cache.put(request,response.clone());}catch{}}return response;};
if(request.mode==='navigate'){try{return await save(await fetch(request));}catch{const cached=await cache.match(request);if(cached)return cached;if(url.pathname===root.pathname||url.pathname===root.pathname+'index.html')return await cache.match(new URL('./index.html',root).href);return Response.error();}}
const cached=await cache.match(request);if(cached)return cached;return save(await fetch(request));})());});
